#!/usr/bin/env sh

. "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

export SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null"

FONT="FiraCode Nerd Font Mono"

PADDINGS=3
SEGMENT_SPACING=13

sketchybar --bar height=24 \
    corner_radius=0 \
    border_width=0 \
    margin=0 \
    blur_radius=0 \
    position=top \
    padding_left=4 \
    padding_right=4 \
    topmost=off \
    sticky=on \
    font_smoothing=off \
    y_offset=-100 \
    notch_width=0 \
    \
    --default drawing=on \
    updates=when_shown \
    label.font="$FONT:Bold:16.0" \
    icon.font="$FONT:Bold:18.0" \
    icon.padding_left=$PADDINGS \
    icon.padding_right=$PADDINGS \
    label.padding_left=$PADDINGS \
    label.padding_right=$PADDINGS \
    background.padding_right=$PADDINGS \
    background.padding_left=$PADDINGS

sketchybar --animate sin 30 --bar y_offset=-100 y_offset=0
sketchybar --add event theme_changed AppleInterfaceThemeChangedNotification
sketchybar --add item colordummy center \
    --set colordummy \
    drawing=off \
    script="$PLUGIN_DIR/colordummy.sh" \
    --subscribe colordummy theme_changed

### Template for some elements ###
sketchybar --add item label_template left \
    --set label_template icon.drawing=off \
    label.font="$FONT:Normal:16.0" \
    label.padding_right=5 \
    click_script="$PLUGIN_DIR/toggle_bracket.sh" \
    background.padding_left=$SEGMENT_SPACING \
    drawing=off

### Spaces themselves are this ###
. "$ITEM_DIR/spaces.sh"

### First Seperator on the bar ###
sketchybar --add item separator left \
    --set separator icon=┃ \
    icon.font="$FONT:Regular:9.0" \
    background.padding_left=-5 \
    background.padding_right=-7 \
    icon.y_offset=1 \
    label.drawing=off

sketchybar --add event window_focus \
    --add item system.yabai left \
    --set system.yabai script="$PLUGIN_DIR/yabai.sh" \
    icon.font="$FONT:Bold:14.0" \
    label.drawing=off \
    icon.y_offset=1 \
    icon.padding_left=8 \
    updates=on \
    --subscribe system.yabai window_focus mouse.clicked

sketchybar --add item separator2 left \
    --set separator2 icon=┃ \
    icon.font="$FONT:Regular:9.0" \
    background.padding_right=0 \
    background.padding_left=-3 \
    icon.y_offset=1 \
    label.drawing=off \
    icon.color=0xff606060

### SPACE NUMBER ###
. "$ITEM_DIR/spacenum.sh"

### Third seperator on the bar ###
sketchybar --add item separator3 left \
    --set separator3 icon=┃ \
    icon.font="$FONT:Regular:9.0" \
    background.padding_right=-5 \
    icon.y_offset=1 \
    label.drawing=off \
    icon.color=0xff606060

sketchybar --add event window_focus \
    --add event title_change \
    --add item title left \
    --set title script="$PLUGIN_DIR/window_title.sh" \
    label.font="$FONT:Bold:11.8" \
    label.y_offset=1 \
    label.padding_left=-0  \
    label.color=0xffd5d9dd \
    --subscribe title window_focus front_app_switched space_change title_change

### MENU BAR ITEMS ###
. "$ITEM_DIR/system.sh"

### CLOCK WIDGET ###
sketchybar --add item clock right \
    --set clock update_freq=1 \
    icon="$CLOCK" \
    icon.font="$FONT:Bold:13" \
    icon.padding_right=4 \
    icon.y_offset=2 \
    label.y_offset=1 \
    label.font="$FONT:Bold:12" \
    label.color=0xff55d0f0 \
    background.height=2 \
    background.padding_right=6 \
    background.y_offset=-9 \
    script="$PLUGIN_DIR/clock.sh" \
    icon.padding_left=0 \
    label.padding_right=1

### BATTERY WIDGET ###
sketchybar --add item battery right \
    --set battery update_freq=2 \
    icon.font="$FONT:Bold:13.0" \
    icon.padding_right=3 \
    icon.y_offset=2 \
    icon.y_offset=1 \
    label.font="$FONT:Bold:12.0" \
    label.padding_right=8 \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/battery.sh" \
    icon.padding_left=0 \
    label.padding_right=0

### UPDATES WIDGET ###
sketchybar --add item updates right \
    --set updates update_freq=1800 \
    icon="$BELL" \
    icon.font="$FONT:Bold:13" \
    icon.padding_right=7 \
    icon.y_offset=1 \
    label.y_offset=1 \
    label.font="$FONT:Bold:10.6" \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/package_monitor.sh" \
    icon.padding_left=0 label.padding_right=2

### UPTIME WIDGET ###
sketchybar --add item uptime right \
    --set uptime update_freq=120 \
    icon.font="$FONT:Bold:13" \
    icon.padding_right=4 \
    label.y_offset=1 \
    icon.y_offset=1 \
    label.font="$FONT:Bold:10.6" \
    label.padding_right=8 \
    background.color=0xff9bbf70 \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/uptime.sh" \
    icon.padding_left=0 label.padding_right=2

### ssd Widget ###
sketchybar --add item ssd right \
    --set ssd update_freq=10 \
    icon.padding_right=4 \
    icon.font="$FONT:Bold:13" \
    icon.y_offset=1 \
    label.y_offset=1 \
    label.font="$FONT:Bold:10.6" \
    label.padding_right=8 \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/disk.sh" \
    icon.padding_left=0 label.padding_right=2

### mem Widget ###
sketchybar --add item mem right \
    --set mem update_freq=10 \
    icon.font="$FONT:Bold:13" \
    icon.padding_right=4 \
    icon.y_offset=1 \
    label.y_offset=1 \
    label.font="$FONT:Bold:10.6" \
    label.padding_right=8 \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/mem.sh" \
    icon.padding_left=0 label.padding_right=2

### cpu Widget ###
sketchybar --add item cpu right \
    --set cpu update_freq=10 \
    icon.font="$FONT:Bold:13" \
    icon.padding_right=4 \
    icon.y_offset=1 \
    label.y_offset=1 \
    label.font="$FONT:Bold:10.6" \
    label.padding_right=8 \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/cpu.sh" \
    icon.padding_left=0 label.padding_right=2

### os version Widget ###
sketchybar --add item ver right \
    --set ver update_freq=6400 \
    icon.font="$FONT:Bold:13" \
    icon.padding_right=4 \
    icon.y_offset=1 \
    label.y_offset=1 \
    label.font="$FONT:Bold:10.6" \
    label.padding_right=8 \
    background.height=2 \
    background.y_offset=-9 \
    background.padding_right=8 \
    script="$PLUGIN_DIR/os-ver.sh" \
    icon.padding_left=-1 label.padding_right=2

### If an update is avalible, update sketchybar when launched ##
sketchybar --hotload true
sketchybar --update

### Notify when sketchybarrc is finished loading ##
echo "sketchybar configuation loaded.."
