#!/bin/bash

# To uninstall, run the two following commands
# brew uninstall sketchybar
# brew untap FelixKratz/formulae

source "$HOME/.config/sketchybar/icons.sh"

FONT="BigBlue_Terminal_437TT Nerd Font" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3
POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
CORNER_RADIUS=15
SHADOW=on
BAR_HEIGHT=32

BAR_COLOR=0xFFFDDDE6
BORDER_COLOR=0xFFFBAED2

bar=(
    height="$BAR_HEIGHT"
    border_color="$BORDER_COLOR"
    color="$BAR_COLOR"
    shadow="$SHADOW"
    sticky=on
    padding_top=5
    padding_bottom=5
    padding_right="$PADDINGS"
    padding_left=0
    corner_radius="$CORNER_RADIUS"
    y_offset=0
    margin=0
    notch_width=200
    blur_radius=20
)

sketchybar --bar "${bar[@]}"

default=(
    icon.font="$FONT:Nerd Font Mono:14.0"
    icon.color=0xFFFBAED2
    icon.padding_left="$PADDINGS"
    icon.padding_right="$PADDINGS"
    label.font="$FONT:Nerd Font Mono:13.0"
    label.color=0xFFFBAED2
    label.padding_left="$PADDINGS"
    label.padding_right="$PADDINGS"
    background.padding_left="$PADDINGS"
    background.padding_right="$PADDINGS"
    popup.background.border_width=2
    popup.background.corner_radius=11
    popup.background.border_color="$BORDER_COLOR"
    popup.background.color="$BAR_COLOR"
    popup.background.shadow.drawing="$SHADOW"
    scroll_texts=on
    updates=when_shown
)

sketchybar --default "${default[@]}"

APPLE_POPUP_OFF="sketchybar --set apple.logo popup.drawing=off"
APPLE_POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"

sketchybar --add item apple.logo left \
    --set apple.logo icon="🍏" \
    icon.font="$FONT:Black:16.0" \
    icon.padding_left=10 \
    icon.padding_right=10 \
    background.padding_left=-1 \
    background.height=26 \
    background.padding_right=17 \
    background.corner_radius="$CORNER_RADIUS" \
    label.drawing=off \
    click_script="$APPLE_POPUP_CLICK_SCRIPT" \
    --add item apple.prefs popup.apple.logo \
    --set apple.prefs icon="$PREFERENCES" \
    label="Preferences" \
    click_script="open -a 'System Preferences';
    $APPLE_POPUP_OFF" \
        \
        --add item apple.activity popup.apple.logo \
        --set apple.activity icon=$ACTIVITY \
        label="Activity" \
        click_script="open -a 'Activity Monitor';
            $APPLE_POPUP_OFF" \
                \
                --add item apple.lock popup.apple.logo \
                --set apple.lock icon=$LOCK \
                label="Lock Screen" \
                click_script="pmset displaysleepnow;
                            $APPLE_POPUP_OFF"

sketchybar --update
echo "sketchybar configuration loaded..."
