#!/usr/bin/env bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="Liga SFMono Nerd Font"

bar=(
    corner_radius=25
    display=all
    font_smoothing=off
    height=39
    hidden=off
    margin=15
    notch_offset=0
    notch_width=200
    padding_left=5
    padding_right=5
    position=top
    shadow=off
    sticky=on
    topmost=off
    y_offset=7
)

sketchybar --bar "${bar[@]}"

sketchybar --add event theme_changed AppleInterfaceThemeChangedNotification \
           --add item colordummy left \
           --set colordummy \
                 icon.drawing=off \
                 label.drawing=off \
                 script="$PLUGIN_DIR/colordummy.sh" \
           --subscribe colordummy theme_changed

defaults=(
    updates=when_shown
    drawing=on
    icon.font="$FONT:Bold:18.0"
    label.font="Liga SFMono Nerd Font:Regular:16.0"
    icon.align=center
    label.padding_left=1
    label.padding_right=1
    icon.padding_left=8
    icon.padding_right=8
)

sketchybar --default "${defaults[@]}"

SPACE_ICONS=("" "" "󰛮" "" "󰈈" "󰆼" "󰉋" "󰝚" "󰡨" "10")

for i in "${!SPACE_ICONS[@]}"
do
    if [[ $i ==  0 ]]; then
        lbgp=0
    else
        lbgp=1
    fi

    sketchybar \
        --add space "space.$i" left \
        --set "space.$i" associated_space=$(($i+1)) \
                         icon="${SPACE_ICONS[i]}" \
                         icon.padding_left=8 \
                         icon.padding_right=8 \
                         background.padding_left="$1bgp" \
                         background.padding_right=1 \
                         background.height=32 \
                         label.drawing=off \
                         script="$PLUGIN_DIR/space.sh" \
                         click_script="yabai -m space --focus $(($i+1))"
    done

sketchybar --add item window_title left \
           --set window_title \
                 background.padding_left=8 \
                 script="$PLUGIN_DIR/window_title.sh" \
           --subscribe window_title front_app_switched

sketchybar --add event song_update com.apple.Music.playerInfo
sketchybar \
    --add item music center \
    --set music label.font="Victor Mono:Bold Italic:16.0" \
                script="$PLUGIN_DIR/music.sh" \
                display=1 \
    --subscribe music song_update

sketchybar --add item clock right \
    --set clock \
    script="$PLUGIN_DIR/clock.sh" \
    update_freq=10

sketchybar --add item date right \
    --set date \
    script="$PLUGIN_DIR/date.sh" \
    update_freq=60

sketchybar --add item battery right \
    --set battery \
    update_freq=30 \
    script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke

sketchybar --add item sound right \
    --set sound \
    script="$PLUGIN_DIR/volume.sh" \
    display=1 \
    update_freq=5

##### Finalizing Setup #####
sketchybar --update
sketchybar --hotload on
