- link:
    ~/.asdfrc: package-managers/asdf/asdfrc
    ~/.tool-versions: package-managers/asdf/tool-versions
    ~/.default-gems: package-managers/asdf/default-gems.txt
    ~/.default-pnpm-packages: package-managers/asdf/default-pnpm-packages.txt
    ~/.default-python-packages: package-managers/asdf/default-python-packages.txt

- shell:
    - description: Setting up ASDF
      quiet: true
      command: >-
            chmod +x ~/.dotfiles/commands/asdf-install.sh;
            ~/.dotfiles/commands/asdf-install.sh
