# vim: set filetype=yaml ts=4 sw=4 tw=0 et :
- shell:
    - description: Installing asdf
      command: |
          brew list asdf >/dev/null || brew install asdf
      stdout: true
      stderr: true
- link:
    ~/.asdfrc: tools/package-managers/asdf/asdfrc
    ~/.tool-versions: tools/package-managers/asdf/tool-versions
    ~/.default-gems: tools/package-managers/asdf/default-gems
    ~/.default-npm-packages: tools/package-managers/asdf/default-npm-packages
    ~/.default-python-packages: tools/package-managers/asdf/default-python-packages

- asdf:
    - plugin: erlang
      url: https://github.com/asdf-vm/asdf-erlang.git
    - plugin: elixir
    - plugin: elm
    - plugin: rust
    - plugin: python
    - plugin: ruby
      versions:
          - latest
    - plugin: nodejs
      versions:
          - latest
    - plugin: golang
      versions:
          - latest
    - plugin: lua
    - plugin: luajit
      url: https://github.com/smashedtoatoms/asdf-luajit.git
    - plugin: neovim
      versions:
          - nightly

