# --- Base Configuration ---
- defaults:
    link:
      create: true
      force: true
      relink: true
    shell:
      stdout: true
      stderr: true

- create:
  - ~/.config
  - ~/dev
  - ~/code
  - ~/.bin
  - ~/.cache
  - ~/.ssh
  - ~/.local/bin

- clean:
    $HOME:
      force: true
    $HOME/.config:
      recursive: true
