- defaults:
    link:
      create: true
      force: true
      relink: true
    shell:
      stdout: true
      stderr: true
- clean:
    ~/:
      force: true
    ~/.local/bin:
      force: true
    ~/.config:
      recursive: true
- create:
    - ~/.config
    - ~/dev
    - ~/code
    - ~/.bin
    - ~/.cache
    - ~/.ssh
    - ~/.local/bin
- shell:
    - description: Installing submodules
      command: git submodule update --init --recursive
