- defaults:
    link:
        create: true
        relink: true
        force: true

- link:
    ~/.profile: shell/bash/profile
    ~/.bashrc: shell/bash/bashrc
    ~/.bash_aliases: shell/bash/bash_aliases
    ~/.bash_profile: shell/bash/bash_profile
    ~/.bash_logout: shell/bash/bash_logout
