---
# --- Dotfile Binaries Config ---
- link:
    ~/.local/bin:
      glob: true
      path: bin/*
      exclude: [bin/lock-screen, bin/lyrics]
    ~/.local/bin/shim: scripts/shim.sh
- ifmacos:
    - link:
        ~/.local/bin/lock-screen: bin/lock-screen
        ~/.local/bin/lyrics: bin/lyrics
