- tap: [felixkratz/formulae]
- brew: [borders]

- link:
    ~/.config/borders/bordersrc: .config/borders/bordersrc

- shell:
    - description: Kicking off borders service
      quiet: false
      command: >-
        brew services restart borders
