---
# --- Editor Configuration ---
- shell:
    - [asdf install neovim ref:master]
- link:
    ~/.config/nvim: editors/nvim
- shell:
    - [curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
          --profile minimal, Installing Rust]
    - [. ~/.cargo/env && rustup component add rust-src, Adding Rust Source]
- link:
    ~/Library/Application Support/Code/User/settings.json: editors/vscode/settings.json
