# --- Git Configuration ---
- link:
    ~/.gitconfig: tools/vcs/git/config
    ~/.gitattributes: tools/vcs/git/attributes
    ~/.gitmessage: tools/vcs/git/message
    ~/.gitignore_global: tools/vcs/git/ignore
    ~/.gitconfig.local: tools/vcs/git/config.local
    ~/.config/git:
        glob: true
        path: tools/vcs/git/*
        exclude: [ tools/vcs/git/README.md ]

- asdf:
  - plugin: git
    versions:
      - latest
