# --- gnupg Configuration ---

- shell:
    - [mkdir -p ~/.gnupg, Creating gnupg config directory]

- ifanylinux:
    - link:
        ~/.gnupg/gpg.conf: tools/gnupg/gpg.conf
        ~/.gnupg/gpg-agent.conf: tools/gnupg/gpg-agent-linux.conf

- ifmacos:
    - link:
        ~/.gnupg/gpg.conf: tools/gnupg/gpg.conf
        ~/.gnupg/gpg-agent.conf: tools/gnupg/gpg-agent-mac.conf
