- shell:
  - command: |
        ~/.dotfiles/tools/package-managers/brew/install
    description: Installing homebrew
    quiet: false
    stdin: true
- brewfile:
    - tools/package-managers/brew/Brewfile.cask
    - tools/package-managers/brew/Brewfile
