# --- MacOS UI Elements Configuration ---
- tap:
  - koekeishiya/formulae

- asdf:
  - plugin: python

- brew:
  - yabai
  - sketchybar

- cask:
  - dozer
  - hammerspoon

- link:
    ~/.config/yabai/yabairc: gui/yabai/yabairc
    ~/.config/yabai/scripts: gui/yabai/scripts
    ~/.config/sketchybar:
      force: true
      glob: true
      path: gui/sketchybar/*
    ~/.hammerspoon: gui/hammerspoon

- shell:
    - "brew services start sketchybar"
    - "brew services start yabai"
