# --- Neovim Config ---

- asdf:
  - plugin: neovim
    global: nightly
    versions:
      - nightly
  - plugin: python
    global: 3.11.4
    versions:
      - 2.7.18
      - 3.9.0
      - 3.11.4

- link:
    ~/.config/nvim: editors/nvim


- pip:
    file: package-managers/asdf/default-python-packages.txt
    user: true
    stdout: false
    stderr: true
    
