- link:
    ~/.config/sketchybar: os/macos/sketchybar

- shell:
    - description: Setting sketchybar scripts to executable
      quiet: true
      command: >-
        echo "Attempting to set sketchybar scripts to executable";
        chmod +x ~/.config/sketchybar/**/*.sh;

        echo "Restarting sketchybar";
        brew services restart sketchybar;