- tap: [felixkratz/formulae]
  brew: [jq, skhd]

- create:
    - '~/.config/skhd'

- shell:
    - description: Make executable
      command: >-
        chmod +x .config/skhd/skhdrc && chmod +x .config/skhd/focus_recent.sh

- link:
    ~/.skhdrc: .config/skhd/skhdrc
    ~/.config/skhd/focus_recent.sh: .config/skhd/focus_recent.sh

- shell:
    - description: Starting skhd
      command: >-
        skhd --restart-service;
