local M = {}

-- ---Recursively build a nested table from a list of keys and a value
-- ---@param key_parts string[] list of keys
-- ---@param val any
-- ---@return table
-- function M.build_nested(key_parts, val)
--   return key_parts[1]
--     and { [key_parts[1]] = M.build_nested({ table.unpack(key_parts, 2) }, val) }
--     or val
-- end
--
-- ---@class parsed_arg_t table
-- ---Parse arguments from the command line into a table
-- ---@param fargs string[] list of arguments
-- ---@return table
-- function M.parse_cmdline_args(fargs)
--   local parsed = {}
--   -- First pass: parse arguments into a plain table
--   for _, arg in ipairs(fargs) do
--     local key, val = arg:match('^%-%-(%S+)=(.*)$')
--     if not key then
--       key = arg:match('^%-%-(%S+)$')
--     end
--
--     -- Handle val_expanded as an array
--     local val_expanded = vim.fn.expand(val)
--     if type(val_expanded) == 'table' then
--       for _, v in ipairs(val_expanded) do
--         if vim.fn.filereadable(v) == 1 then
--           val = v
--           break
--         end
--       end
--     else
--       -- If it's a single string, check if it's a file
--       if vim.fn.filereadable(val_expanded) == 1 then
--         val = val_expanded
--       end
--     end
--
--     if key and val then -- '--key=value'
--       local eval_valid, eval_result = pcall(vim.fn.eval, val)
--       parsed[key] = not eval_valid and val or eval_result
--     elseif key and not val then -- '--key'
--       parsed[key] = true
--     else -- 'value'
--       table.insert(parsed, val)
--     end
--   end
--   -- Second pass: build nested tables from dot-separated keys
--   for key, val in pairs(parsed) do
--     if type(key) == 'string' then
--       local key_parts = vim.split(key, '%.')
--       parsed =
--       vim.tbl_deep_extend('force', parsed, M.build_nested(key_parts, val))
--       if #key_parts > 1 then
--         parsed[key] = nil -- Remove the original dot-separated key
--       end
--     end
--   end
--   return parsed
-- end

return M
