-- Exported functions
local M = {}

-- function M.fg(name)
--   local hl = vim.fn.gethlbyname(name, true)
--   local fg = hl and hl.fg and hl.foreground
--   return fg and { fg = string.format("#%06x", fg) }
-- end
--
-- function M.on_very_lazy(fn)
--   vim.api.nvim_create_autocmd("User", {
--     pattern = "VeryLazy",
--     callback = function()
--       fn()
--     end,
--   })
-- end
--
-- -- returns the root directory based on:
-- -- * lsp workspace folders
-- -- * lsp root_dir
-- -- * root pattern of filename of the current buffer
-- -- * root pattern of cwd
-- ---@return string
-- function M.get_root()
--   ---@type string?
--   local path = vim.api.nvim_buf_get_name(0)
--   path = path ~= "" and vim.fn.resolve(path) or nil
--
--   ---@type string[]
--   local roots = {}
--   if path then
--     for _, client in pairs(vim.lsp.get_clients({ bufnr = 0 })) do
--       local workspace = client.config.workspace_folders
--       local paths = workspace and vim.tbl_map(function(ws)
--         return vim.uri_to_fname(ws.uri)
--       end, workspace) or client.config.root_dir and { client.config.root_dir } or {}
--       for _, p in ipairs(paths) do
--         local r = vim.fn.resolve(p)
--         if path:find(r, 1, true) then
--           roots[#roots + 1] = r
--         end
--       end
--     end
--   end
--   table.sort(roots, function(a, b)
--     return #a > #b
--   end)
--
--   ---@type string?
--   local root = roots[1]
--   if not root then
--     path = path and vim.fs.dirname(path) or vim.fn.getcwd()
--     ---@type string?
--     root = vim.fs.find(M.root_patterns, { path = path, upward = true})[1]
--     root = root and vim.fs.dirname(root) or vim.fn.getcwd()
--   end
--   return root
-- end
--
-- -- this will return a function that calls telescope.
-- -- cwd will default to lazyvim.util.get_root
-- -- for `files`, git_files or find_files will be chosen depending on .git
-- function M.telescope(builtin, opts)
--   local params = { builtin = builtin, opts = opts }
--   return function()
--     builtin = params.builtin
--     opts = params.opts
--     opts = vim.tbl_deep_extend("force", { cwd = M.get_root() }, opts or {})
--     if builtin == "files" then
--       if vim.fn.resolve((opts.cwd or vim.fn.getcwd()) .. "/.git") then
--         opts.show_untracked = true
--         builtin = "git_files"
--       else
--         builtin = "find_files"
--       end
--     end
--     if opts.cwd and opts.cwd ~= vim.fn.getcwd() then
--       opts.attach_mappings = function(_, map)
--         map("i", "<a-c>", function()
--           local action_state = require("telescope.actions.state")
--           local line = action_state.get_current_line()
--           M.telescope(
--             params.builtin,
--             vim.tbl_deep_extend("force", {}, params.opts or {}, { cwd = false, default_text = line })
--           )()
--         end)
--         return true
--       end
--     end
--
--     require("telescope.builtin")[builtin](opts)
--   end
-- end
--
-- local terminals = {}
--
-- -- Opens a floating terminal (interactive by default)
-- function M.float_term(cmd, opts)
--   opts = vim.tbl_deep_extend("force", {
--     ft = "lazyterm",
--     size = { width = 0.9, height = 0.9 },
--   }, opts or {}, { persistent = true })
--
--   local termkey = vim.inspect({ cmd = cmd or "shell", cwd = opts.cwd, env = opts.env, count = vim.v.count1 })
--
--   if terminals[termkey] and terminals[termkey]:buf_valid() then
--     terminals[termkey]:toggle()
--   else
--     terminals[termkey] = require("utils.functions").float_term(cmd, opts)
--     local buf = terminals[termkey].buf
--     vim.b[buf].lazyterm_cmd = cmd
--     if opts.esc_esc == false then
--       vim.keymap.set("t", "<esc>", "<esc>", { buffer = buf, nowait = true })
--     end
--     if opts.ctrl_hjkl == false then
--       vim.keymap.set("t", "<c-h>", "<c-h>", { buffer = buf, nowait = true })
--       vim.keymap.set("t", "<c-j>", "<c-j>", { buffer = buf, nowait = true })
--       vim.keymap.set("t", "<c-k>", "<c-k>", { buffer = buf, nowait = true })
--       vim.keymap.set("t", "<c-l>", "<c-l>", { buffer = buf, nowait = true })
--     end
--
--     vim.api.nvim_create_autocmd("BufEnter", {
--       buffer = buf,
--       callback = function()
--         vim.cmd.startinsert()
--       end,
--     })
--   end
--
--   return terminals[termkey]
-- end
--
-- ---@param silent boolean?
-- ---@param values? {[1]:any, [2]:any}
-- function M.toggle(option, silent, values)
--   if values then
--     if vim.opt_local[option]:get() == values[1] then
--       vim.opt_local[option] = values[2]
--     else
--       vim.opt_local[option] = values[1]
--     end
--     return require("utils.notify").info("Set " .. option .. " to " .. vim.opt_local[option]:get(), { title = "Option" })
--   end
--   vim.opt_local[option] = not vim.opt_local[option]:get()
--   if not silent then
--     if vim.opt_local[option]:get() then
--       require("utils.notify").info("Enabled " .. option, { title = "Option" })
--     else
--       require("utils.notify").warn("Disabled " .. option, { title = "Option" })
--     end
--   end
-- end
--
-- -- delay notifications till vim.notify was replaced or after 500ms
-- function M.lazy_notify()
--   local notifs = {}
--   local function temp(...)
--     table.insert(notifs, vim.F.pack_len(...))
--   end
--
--   local orig_notify = vim.notify
--   vim.notify = temp
--
--   local function delayed_notification()
--     if vim.notify == temp then
--       vim.notify = orig_notify
--     end
--     for _, notif in ipairs(notifs) do
--       vim.notify(vim.F.unpack_len(notif))
--     end
--   end
--
--   vim.defer_fn(delayed_notification, 500)
-- end


return M
