local M = {}

-- ---highlight group if it doesn't exist
-- ---@param buffer integer buffer handle, or 0 for current buffer
-- ---@param ns_id integer namespace to use or -1 for ungrouped highlight
-- ---@param hl_group string name of the highlight group to use
-- ---@param line integer line to highlight (zero-indexed)
-- ---@param col_start integer start of (byte-indexed) column range to highlight
-- ---@param col_end integer end of (byte-indexed) column range to highlight, or -1 to highlight to end of line
-- ---@return nil
-- function M.buf_add_hl(buffer, ns_id, hl_group, line, col_start, col_end)
--   if vim.fn.hlexists(hl_group) == 0 then
--     return
--   end
--   vim.api.nvim_buf_add_highlight(
--     buffer,
--     ns_id,
--     hl_group,
--     line,
--     col_start,
--     col_end
--   )
-- end
--
-- ---Highlight text in buffer, clear previous highlight if any exists
-- ---@param buf integer
-- ---@param hlgroup string
-- ---@param range winbar_symbol_range_t?
-- function M.range_single(buf, hlgroup, range)
--   local ns = vim.api.nvim_create_namespace(hlgroup)
--   vim.api.nvim_buf_clear_namespace(buf, ns, 0, -1)
--   if range then
--     for linenr = range.start.line, range['end'].line do
--       local start_col = linenr == range.start.line and range.start.character
--       or 0
--       local end_col = linenr == range['end'].line and range['end'].character
--       or -1
--       M.buf_add_hl(buf, ns, hlgroup, linenr, start_col, end_col)
--     end
--   end
-- end
--
-- ---Highlight a line in buffer, clear previous highlight if any exists
-- ---@param buf integer
-- ---@param hlgroup string
-- ---@param linenr integer? 1-indexed line number
-- function M.line_single(buf, hlgroup, linenr)
--   M.range_single(buf, hlgroup, linenr and {
--     start = {
--       line = linenr - 1,
--       character = 0,
--     },
--     ['end'] = {
--       line = linenr - 1,
--       character = -1,
--     },
--   })
-- end
--
-- ---Merge highlight attributes, use values from the right most hl group
-- ---if there are conflicts
-- ---@vararg string highlight group names
-- ---@return table merged highlight attributes
-- function M.merge(...)
--   -- Eliminate nil values in vararg
--   local hl_names = {}
--   for _, hl_name in pairs({ ... }) do
--     if hl_name then
--       table.insert(hl_names, hl_name)
--     end
--   end
--   local hl_attr = vim.tbl_map(function(hl_name)
--     return M.get_hl(0, {
--       name = hl_name,
--       link = false,
--     })
--   end, hl_names)
--   return vim.tbl_extend('force', table.unpack(hl_attr))
-- end
--
return M
