return {
  diagnostics = {
    error = " ",
    hint = " ",
    information = " ",
    other = " ",
    warning = " ",
  },
  git = {
    Added = " ",
    Modified = " ",
    Removed = " ",
  },
  dap = {
    breakpoint = " ",
    breakpoint_condition = " ",
    log_point = " ",
    stopped = " ",
    breakpoint_rejected = " ",
    pause = " ",
    play = " ",
    step_into = " ",
    step_over = " ",
    step_out = " ",
    step_back = " ",
    run_last = " ",
    terminate = " ",
  },
  lazy = {
    cmd = " ",
    config = "",
    event = "",
    ft = " ",
    init = " ",
    import = " ",
    keys = " ",
    lazy = "󰒲 ",
    loaded = "󱄲",
    not_loaded = "󱄯",
    plugin = " ",
    runtime = " ",
    source = " ",
    start = "",
    task = "✔ ",
    list = {
      "󱄰",
      "➜",
      "★",
      "‒",
    },
  },
  mason = {
    package_installed = "󱄲",
    package_pending = "󱄰",
    package_uninstalled = "󱄯",
  },
  trouble = {
    indent = {
      top = "┊ ",
      middle = "├╴",
      last = "└╴",
      fold_open = " ",
      fold_closed = " ",
      ws = "  ",
    },
    folder_closed = " ",
    folder_open = " ",
    kinds = {
      Array = " ",
      Boolean = "󰨙 ",
      Class = " ",
      Constant = "󰏿 ",
      Constructor = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Function = "󰊕 ",
      Interface = " ",
      Key = " ",
      Module = " ",
      Namespace = "󰦮 ",
      Null = " ",
      Number = "󰎠 ",
      Object = " ",
      Operator = " ",
      Package = " ",
      Property = " ",
      String = " ",
      Struct = "󰆼 ",
      TypeParameter = " ",
      Variable = "󰀫 ",
      Text = "",
      Method = "",
      Unit = "",
      Value = "",
      Keyword = "",
      Snippet = "",
      Color = "",
      Reference = "",
      Folder = "",
      Copilot = "",
    },
  },
  borders = {
    dashed = { "┄", "┊", "┄", "┊", "╭", "╮", "╯", "╰" },
    double = { "═", "║", "═", "║", "╔", "╗", "╝", "╚" },
    single = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
    blocks = { "▀", "▐", "▄", "▌", "▛", "▜", "▟", "▙" },
    blocky = { "▀", "▐", "▄", "▌", "▄", "▄", "▓", "▀" },
    diagflow = {
      top_left = "╭",
      top_right = "╮",
      bottom_left = "╰",
      bottom_right = "╯",
      horizontal = "╌",
      vertical = "┊",
    },
  },
  telescope = {
    prompt = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
    results = { "─", " ", "─", "│", "╭", "─", "─", "╰" },
    preview = { "─", "│", "─", "│", "─", "╮", "╯", "╰" },
  },
  snacks = {
    snack = "󰉚 ",
    new = " ",
    old = " ",
    findf = "󰥨 ",
    findt = " ",
    git = " ",
    lazy = "󰒲 ",
    mason = "󱌣 ",
    prof = "󰄉 ",
    quit = "󰭿 ",
    start = " ",
    plug = " ",
    spell = "",
    wrap = "󰖶",
    chunk = {
      corner_top = "┌",
      corner_bottom = "└",
      horizontal = "┄",
      vertical = "┊",
      arrow = "┄",
    },
  },
}
