#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIGDIR="${BASEDIR}/meta/configs"
PROFILESDIR="${BASEDIR}/meta/profiles"
DOTBOT="${BASEDIR}/meta/dotbot/bin/dotbot"

declare -a ARGS
declare -a FLAGS
while (("$#")); do
    case "$1" in
        -*)
            FLAGS+=("$1")
            ;;
        *)
            ARGS+=("$1")
            ;;
    esac
    shift
done
set -- "${ARGS[@]}"

declare -a CONFIGS
while IFS= read -r config; do
    if [[ -n "$config" ]]; then
        CONFIGS+=("${config}")
    fi
done <"${PROFILESDIR}/$1"
shift

for config in "${CONFIGS[@]}" "${@}"; do
    echo -e "Adding configuration $config"
    CONFIGCONTENT="${CONFIGCONTENT}\n$(<"${CONFIGDIR}/${config}.yaml")"
done

if [[ "${#FLAGS[@]}" -gt 0 ]]; then
    "${DOTBOT}" "${FLAGS[@]}" -d "${BASEDIR}" -c <(echo -e "${CONFIGCONTENT}")
else
    "${DOTBOT}" -d "${BASEDIR}" -c <(echo -e "${CONFIGCONTENT}")
fi
