#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yml"

VENDOR_DIR="vendor"
META_DIR="meta"
CONFIG_DIR="configs"

DOTBOT_DIR="vendor/dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive --remote

for config in "${@}"; do
  configFile="$(mktemp)"
  echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")" >"$configFile"
  "${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${VENDOR_DIR}/dotbot-brew" --plugin-dir "${VENDOR_DIR}/dotbot-asdf" -c "$configFile"
  rm -f "$configFile"
done
