#!/bin/sh

trap "printf '\nCaught ^C from user - exiting now\n' ; exit 130" INT

this_path=$(cd "$(dirname "$0")" && pwd)
bin_path="$this_path/bin"

"$bin_path/setup_fonts"
"$bin_path/setup_code"
"$bin_path/setup_continue"
