#!/usr/bin/env zsh

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

defaults write .GlobalPreferences com.apple.mouse.scaling -1

BAR_HEIGHT=$(sketchybar --query bar | jq -r '.height')

GENERAL=(
  external_bar all:"${BAR_HEIGHT}":0
  split_type   auto
  split_ratio  0.5
  auto_balance off
)

WINDOWS=(
  window_placement          second_child
  window_topmost            off
  window_shadow             float
  window_opacity            on
  active_window_opacity     0.97
  normal_window_opacity     0.92
  window_animation_duration 0.25
  window_origin_display     focused
  window_opacity_duration   0.15
)

LAYOUT=(
  layout         bsp
  top_padding    15
  bottom_padding 15
  left_padding   15
  right_padding  15
  window_gap     15
)

MOUSE=(
  mouse_modifier      ctrl
  mouse_action1       move
  mouse_action2       resize
  mouse_action3       swap
  mouse_follows_focus off
  focus_follows_mouse off
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"

LABELS=(
  browser
  terminal
  notes
  social
  productivity
  music
)

yabai -m config --space 6 layout float

# Web Browsers
yabai -m rule --add app="^Google Chrome|Safari|Brave Browser$" space=1

# Terminal
yabai -m rule --add app="^(iTerm2|Terminal|Alacritty|kitty|WezTerm)$" space=2

# Notes
yabai -m rule --add app="^(Notion|Obsidian|Notes|Reminders|Craft)$" space=3

# Social
yabai -m rule --add app="^(WhatsApp|Messages|Slack|Discord|Signal|Zoom)$" space=4

# Productivity
yabai -m rule --add app="^(Mail|Keynote|Numbers|Pages|Calendar|Fantastical|Drafts|Things)$" space=5

# Music
yabai -m rule --add app="^(Music|Spotify)$" space=6

# apps to not manage (ignore)
yabai -m rule --add app="^(Finder|System Settings|Archive Utility|Creative Cloud|Logi Options|Raycast|Bitwarden|CleanMyMac X|Karabiner-Elements|Karabiner-EventViewer|Setapp|Stats|ClearVPN|DBngin|FaceTime|Loom|Tape|Alfred|Raycast|Installer|Docker)$" manage=off

echo "yabai configuration loaded.."


for ((i = 1; i <= "${#LABELS[@]}"; i++)); do
  yabai -m space "${i}" --label "${LABELS[(($i - 1))]}"
done

yabai -m config --space social layout stack window_opacity off
yabai -m config --space mail layout stack window_opacity off
yabai -m config --space media layout stack window_opacity off
yabai -m config --space misc layout float


UNMANAGED=(
  Activity Monitor
  App Store
  Archive Utility
  Authy
  Calculator
  Calendar
  Dictionary
  Discord
  Docker
  FaceTime
  Finder
  Mail
  Messages
  Messenger
  Notes
  Photo Booth
  Raycast
  Raycast Preferences
  Screen Sharing
  Screens
  Signal
  Slack
  Software Update
  Spark
  Spotify
  Stats
  System Information
  System Preferences
  System Settings
  Telegram
  Thunderbird
  VLC
  Vimac
  iStat Menus
  zoom.us
  Zoom
)

for ((i = 1; i <= "${#UNMANAGED[@]}"; i++)); do
  yabai -m rule --add label="unmanage_${UNMANAGED[(($i - 1))]}" app="^${UNMANAGED[(($i - 1))]}.*$" manage=off
done

# Exclude problematic apps from being managed
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

SOCIAL=(
  Discord
  FaceTime
  Messages
  Messenger
  Signal
  Slack
  Telegram
)

for ((i = 1; i <= "${#SOCIAL[@]}"; i++)); do
  yabai -m rule --add label="social_${SOCIAL[(($i - 1))]}" app="^${SOCIAL[(($i - 1))]}.*$" space=social
done

MAIL=(
  Mail
  Thunderbird
  Canary
  Spark
)

for ((i = 1; i <= "${#MAIL[@]}"; i++)); do
  yabai -m rule --add label="mail_${MAIL[(($i - 1))]}" app="^${MAIL[(($i - 1))]}.*$" space=mail
done

MEDIA=(
  Music
  Plex
  Spotify
  VLC
)

for ((i = 1; i <= "${#MEDIA[@]}"; i++)); do
  yabai -m rule --add label="media_${MEDIA[(($i - 1))]}" app="^${MEDIA[(($i - 1))]}.*$" space=media
done

# Notes
NOTES=(
	Notes
	Reminders
	Calendar
	Fantastical
)

for ((i = 1; i <= "${#NOTES[@]}"; i++)); do
	yabai -m rule --add label="notes_${NOTES[(($i - 1))]}" app="^${NOTES[(($i - 1))]}.*$" space=notes
done

yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_destroyed action="echo \"destroyed window with id \$YABAI_WINDOW_ID\""
yabai -m signal --add event=space_changed action="echo \"changed space \$YABAI_RECENT_SPACE_ID -> \$YABAI_SPACE_ID\""
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

echo "yabai configuration loaded.."
