- defaults:
    link:
        create: true
        force: true
        relink: true
    shell:
        stdout: true
        stderr: true

- create:
    - $HOME/.config

- clean:
    $HOME:
        force: true
    $HOME/.config:
        recursive: true
# vim: set filetype=yaml ts=4 sw=4 tw=0 et :
