- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdout: true
      stderr: true
- clean: ["~"]
- shell:
    - description: Installing submodules
      command: git submodule update --init --recursive
