# --- Base Configuration ---
- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdout: true
      stderr: true

- clean:
    ~/:
      force: true
    ~/.local/bin:
      force: true
    ~/.config:
      recursive: true

- create:
  - ~/.config
  - ~/.local/bin
