- defaults:
    link:
      create: true
      relink: true
      force: true
    shell:
      stdout: true
      stderr: true

- create:
    - ~/.local/bin
    - ~/Downloads
    - $HOME/.config

- clean:
    $HOME:
        force: true
    $HOME/.config:
        recursive: true
