#!/bin/bash

if [ -x /usr/local/bin/spotifyd ]; then
    exec /usr/local/bin/spotifyd "$@"
elif [ -x /usr/bin/spotifyd ]; then
    exec /usr/bin/spotifyd "$@"
elif [ -x /opt/homebrew/bin/spotifyd ]; then
    exec /opt/homebrew/bin/spotifyd "$@"
else
    echo "spotifyd not found" >&2
    exit 1
fi
