local km = require("key-menu")
vim.o.timeoutlen = 500

local setkey = km.set
vim.o.timeoutlen = 300

setkey("n", "<Leader>")
setkey("n", "<Leader><Leader>", { desc = "Do node action" })
setkey("n", "<Leader>c", { desc = "Config" })
setkey("n", "<Leader>ch", { desc = "Config - Highlight" })
setkey("n", "<Leader>cs", { desc = "Config - Scrollbar" })
setkey("n", "<Leader>ct", { desc = "Config - Themes" })
setkey("n", "<Leader>d", { desc = "Debug" })
setkey("n", "<Leader>f", { desc = "Find" })
setkey("n", "<Leader>fn", { desc = "npm" })
setkey("n", "<Leader>g", { desc = "Git" })
setkey("n", "<Leader>j", { desc = "Jump to Tab" })
setkey("n", "<Leader>l", { desc = "Lsp" })
setkey("n", "<Leader>n", { desc = "Testing" })
setkey("n", "<Leader>o", { desc = "Overseer" })
setkey("n", "<Leader>r", { desc = "Reach" })
setkey("n", "<Leader>u", { desc = "Updates" })
setkey("n", "<Leader>v", { desc = "View" })
setkey("n", "<Leader>w", { desc = "Window" })
setkey("n", "<Leader>ws", { desc = "Window - Move" })
setkey("n", "<Leader>x", { desc = "Trouble" })
setkey("n", "<leader>m", { desc = "Bookmarks" })
setkey("n", "<leader>p", { desc = "Previews" })
setkey("n", "<leader>pp", { desc = "Previews - PlantUML" })
setkey("n", "[")
setkey("n", "]")
setkey("n", "g")
