[project]
name = "treegraft"
vresion = "0.0.0"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
treegraft = "treegraft.main:main"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.7",
]

[tool.ruff.lint]
ignore = ["UP045", "UP007"] # Allow Optional/Union over X | None to support py3.9