local wezterm = require 'wezterm'
local colors = {}
local dark_themes = {
	"astromouse (terminal.sexy)",
	"Banana Blueberry",
	"BirdsOfParadise",
	"BlueBerryPie",
	"Brush Trees Dark (base16)",
	"Butrin (Gogh)",
	"carbonfox",
	"Catppuccin Frappé (Gogh)",
	'Cloud (terminal.sexy)',
	'Colorful Colors (terminal.sexy)',
        'Cloud (terminal.sexy)',
	'cyberpunk',
	'Dark Violet (base16)',
	'Dracula (Gogh)',
	'duskfox',
	'Ef-Duo-Dark',
	'Ef-Melissa-Dark',
	'Eldritch',
	'Erebus (terminal.sexy)',
	'Fairy Floss (Gogh)',
	'Fairy Floss Dark (Gogh)',
	'FarSide (terminal.sexy)',
	'Flatland (Gogh)',
	'ForestBlue',
	'Foxnightly (Gogh)',
	'Framer (base16)',
	'Frontend Fun Forrest (Gogh)',
	'Gigavolt (base16)',
	'GJM (terminal.sexy)',
	'Gooey (Gogh)',
	'Gotham (Gogh)',
	'Grape',
	'Hardcore',
	'hardhacker',
	'Harper',
	'Heetch Dark (base16)',
	'Hemisu Dark (Gogh)',
	'Horizon Dark (base16)',
	'Iceberg (Gogh)',
	'Japanesque',
	'jubi',
	'JWR dark (terminal.sexy)',
	'kanagawabones',
	'Kolorit',
	'Laserwave (Gogh)',
	'lovelace',
	'Lunaria Dark (Gogh)',
	'Mellow Purple (base16)',
	'Mona Lisa (Gogh)',
	'Navy and Ivory (terminal.sexy)',
	'Nebula (base16)',
	'neobones_dark',
	'Neon Night (Gogh)',
	'nightfox',
	'nord',
	'Nova (base16)',
	'NvimDark',
	'Overnight Slumber',
	'Oxocarbon Dark (Gogh)',
	'Palenight (Gogh)',
	'Panda (Gogh)',
	'Paraiso (base16)',
	'Pasque (base16)',
	'Pastel White (terminal.sexy)',
	'Pencil Dark (Gogh)',
	'Peppermint',
	'Pixiefloss (Gogh)',
	'Poimandres',
	'purplepeter',
	'rebecca',
	'rose-pine',
	'rose-pine-moon',
	'Sakura',
	'Sequoia Moonlight',
	'Shades of Purple (base16)',
	'Simple Rainbow (terminal.sexy)',
	'Slate',
	'Snazzy (Gogh)',
	'Splurge (terminal.sexy)',
	'Spring (Gogh)',
	'Square (Gogh)',
	'Sugarplum',
	'Summer Pop (Gogh)',
	'Sweet Eliverlara (Gogh)',
	'Sweet Love (terminal.sexy)',
	'Sweet Terminal (Gogh)',
	'synthwave-everything',
	'Teerb',
	'terafox',
	'Terminix Dark (Gogh)',
	'Thayer Bright (Gogh)',
	'thwump (terminal.sexy)',
	'Tinacious Design (Dark)',
	'tlh (terminal.sexy)',
	'UltraViolent',
	'UnderTheSea',
	'Unikitty Dark (base16)',
	'Vaughn (Gogh)',
	'Vesper',
	'Vice Alt (base16)',
	'Visibone Alt. 2 (terminal.sexy)',
	'Whimsy',
	'Wild Cherry (Gogh)',
	'wilmersdorf',
	'Wryan',
	'Wzoreck (Gogh)',
	'Zenburn',
	'zenburn (terminal.sexy)',
}
local light_themes = {
	"Ashes (light) (terminal.sexy)",
	"Brush Trees (base16)",
	"Catppuccin Latte (Gogh)",
	'Cupcake (base16)',
	'dawnfox',
	'Ef-Kassio',
	'Ef-Summer',
	'Github',
	'Harmonic16 Light (base16)',
	'Heetch Light (base16)',
	'Hemisu Light (Gogh)',
	'Horizon Light (base16)',
	'iceberg-light',
	'Mar (Gogh)',
	'Material Lighter (base16)',
	'Monokai (light) (terminal.sexy)',
	'Mostly Bright (terminal.sexy)',
	'neobones_light',
	'Nord Light (Gogh)',
	'PaperColor Light (base16)',
	'Paraiso (light) (terminal.sexy)',
	'Pencil Light (Gogh)',
	'rose-pine-dawn',
	'Sagelight (base16)',
	'Sakura (base16)',
	'Spring',
	'Summerfruit Light (base16)',
	'Tinacious Design (Light)',
	'Unikitty Light (base16)',
}

local function scheme_for_appearance(appearance)
  if appearance:find 'Dark' then
    return dark_themes[math.random(1, #dark_themes)]
  else
    return light_themes[math.random(1, #light_themes)]
  end
end
--
-- wezterm.on('window-config-reloaded', function(window, pane)
--   if not window:get_config_overrides() then
--     local scheme = scheme_for_appearance(get_appearance())
--     window:set_config_overrides { color_scheme = scheme, }
--   end
-- end)

function colors.apply_to_config(config)
  config.color_scheme = scheme_for_appearance(wezterm.gui.get_appearance())
end

return colors
