[include]
  path = ~/.config/git/conf/alias/util.conf
  path = ~/.config/git/conf/alias/branch.conf
  path = ~/.config/git/conf/alias/commit.conf
  path = ~/.config/git/conf/alias/diff.conf
  path = ~/.config/git/conf/alias/logs.conf
  path = ~/.config/git/conf/alias/misc.conf
  path = ~/.config/git/conf/alias/rebase.conf
  path = ~/.config/git/conf/alias/shorthand.conf
  path = ~/.config/git/conf/alias/status.conf
  path = ~/.config/git/conf/alias/submodule.conf
  path = ~/.config/git/conf/alias/updates.conf

# vim: ft=gitconfig
