[core]
  pager = delta
  fsmonitor = true
  untrackedcache = true
  autocrlf = false
  excludesfile = ~/.gitignore_global
[init]
  defaultBranch = main
[credential]
  helper = store
[fetch]
  # Prune repository when fetching
  prune = true
[checkout]
  defaultRemote = origin
[protocol]
  version = 2
[filter "lfs"]
  clean = git-lfs clean -- %f
  smudge = git-lfs smudge -- %f
  process = git-lfs filter-process
  required = true
[merge]
  tool = vimdiff
  conflictstyle = diff3
[mergetool]
  prompt = false
[mergetool "vimdiff"]
  cmd = nvim -d $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'
[diff]
  colorMoved = default
  tool = vimdiff
[difftool]
  prompt = false
[core]
  pager = delta
[delta]
  features = decorations
  syntax-theme = base16
  side-by-side = true
  line-numbers-left-format = ""
  line-numbers-right-format = "│ "
  line-numbers = true
  navigate = true
[color]
  ui = true
[color "diff-highlight"]
  oldNormal = red bold
  oldHighlight = red bold 52
  newNormal = green bold
  newHighlight = green bold 22
[color "diff"]
  meta = 11
  frag = magenta bold
  func = 146 bold
  commit = yellow bold
  old = red bold
  new = green bold
  whitespace = red reverse
[delta "decorations"]
  commit-decoration-style = bold yellow box ul
  file-style = yellow
  file-decoration-style = bold yellow ul
  hunk-header-decoration-style = yellow box
[interactive]
  # Use delta as the diff filter for interactive mode
  diffFilter = delta --color-only
[gpg]
  format = ssh
[gpg "ssh"]
  program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
[commit]
  gpgsign = true
# vim: ft=gitconfig:
