return {
  { import = "meg.plugins.colorscheme" },
  { import = "meg.plugins.ui" },
  { import = "meg.plugins.dap" },
  { import = "meg.plugins.edit" },
  { import = "meg.plugins.efficiency" },
  { import = "meg.plugins.filetype" },
  { import = "meg.plugins.git" },
  { import = "meg.plugins.lsp" },
  { import = "meg.plugins.mini" },
  { import = "meg.plugins.treesitter" },
  { import = "meg.plugins.tool" },
}
--local lazy = require("meg.plugins.lazy")
--
--vim.g.multigrid = vim.api.nvim_list_uis()[1].ext_multigrid
--
--require("meg.plugins.visual-multi")
--
--local modules = {
--  { "stevearc/resession.nvim", opts = { extensions = { aerial = {} } } },
--  {
--    "stevearc/aerial.nvim",
--    dependencies = {
--      "nvim-treesitter/nvim-treesitter",
--      "nvim-tree/nvim-web-devicons",
--      "hrsh7th/nvim-cmp",
--    },
--    cmd = { "AerialToggle", "AerialOpen" },
--    config = "plugins.aerial",
--  },
--  { "MunifTanjim/nui.nvim" },
--  { "nvim-lua/popup.nvim" },
--  { "nvim-lua/plenary.nvim" },
--  { "nvim-tree/nvim-web-devicons" },
--  {
--    "nvim-telescope/telescope.nvim",
--    cmd = { "Telescope" },
--    dependencies = {
--      "nvim-telescope/telescope-file-browser.nvim",
--      "nvim-lua/plenary.nvim",
--      "kkharji/sqlite.lua",
--      "folke/flash.nvim",
--      {
--        "nvim-telescope/telescope-fzf-native.nvim",
--        build = "cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build",
--      },
--      "TwIStOy/project.nvim",
--    },
--    config = "plugins.telescope",
--  },
--  {
--    "akinsho/toggleterm.nvim",
--    version = "*",
--    init = function() vim.g.toggleterm_terminal_mapping = "<C-t>" end,
--    config = "plugins.toggleterm",
--  },
--  {
--    "tamton-aquib/duck.nvim",
--    keys = {
--      {
--        "<Leader>dd",
--        function() require("duck").hatch("🐈") end,
--        mode = "n",
--        noremap = true,
--        silent = true,
--        desc = "Hatch a duck",
--      },
--      {
--        "<Leader>dk",
--        '<cmd>lua require("duck").cook()<cr>',
--        function() require("duck").cook() end,
--        mode = "n",
--        noremap = true,
--        silent = true,
--        desc = "Cook the duck",
--      },
--    },
--  },
--  { "docunext/closetag.vim", event = "InsertEnter *" },
--  "milisims/nvim-luaref",
--  {
--    "stevearc/pair-ls.nvim",
--    cmd = { "Pair", "PairConnect" },
--    config = true,
--    opts = {
--      cmd = { "pair-ls", "lsp" },
--    },
--  },
--  {
--
--    "folke/zen-mode.nvim",
--    cmd = "ZenMode",
--    opts = {
--      window = {
--        options = {
--          relativenumber = false,
--          number = false,
--        },
--      },
--      plugins = {
--        kitty = {
--          enabled = true,
--          font = "24",
--        },
--      },
--    },
--  },
--
--  {
--    "aznhe21/actions-preview.nvim",
--    event = "VeryLazy",
--    config = function()
--      require("actions-preview").setup({})
--
--      vim.api.nvim_create_autocmd("LspAttach", {
--        desc = "Setup code action preview",
--        callback = function(args)
--          local bufnr = args.buf
--
--          vim.keymap.set(
--            "n",
--            "<leader>la",
--            function() require("actions-preview").code_actions() end,
--            { buffer = bufnr, desc = "LSP: Code action" }
--          )
--        end,
--      })
--    end,
--  },
--  {
--    "mikesmithgh/kitty-scrollback.nvim",
--    cmd = {
--      "KittyScrollbackGenerateKittens",
--      "KittyScrollbackCheckHealth",
--    },
--    event = { "User KittyScrollbackLaunch" },
--    opts = {},
--  },
--  {
--    "kevinhwang91/nvim-fundo",
--    dependencies = "kevinhwang91/promise-async",
--    build = function() require("fundo").install() end,
--    opts = {},
--  },
--  {
--    "jackMort/ChatGPT.nvim",
--    cmd = {
--      "ChatGPT",
--      "ChatGPTActAs",
--      "ChatGPTCompleteCode",
--      "ChtGPTEditWithInstructions",
--      "ChatGPTRun",
--    },
--    cond = vim.env.OPENAI_API_KEY ~= nil,
--    keys = function()
--      local chatgpt = require("chatgpt")
--      local wk = require("which-key")
--
--      wk.register({
--        a = {
--          function() chatgpt.edit_with_instructions() end,
--          "Edit with instructions",
--        },
--      }, { prefix = "<Leader>", mode = "v" })
--
--      return {
--        { "<Leader>cc", "<Cmd>ChatGPT<Cr>", "n", desc = "ChatGPT" },
--        {
--          "<Leader>ce",
--          "<Cmd>ChatGPTEditWithInstruction<Cr>",
--          mode = { "n", "v" },
--          desc = "ChatGPTEditWithInstruction",
--        },
--        {
--          "<Leader>cg",
--          "<Cmd>ChatGPTRun grammar_correction<Cr>",
--          mode = { "n", "v" },
--          desc = "ChatGPTRun grammar_correction",
--        },
--        { "<Leader>ct", "<Cmd>ChatGPTRun translate<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun translate" },
--        { "<Leader>ck", "<Cmd>ChatGPTRun keywords<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun keywords" },
--        { "<Leader>cd", "<Cmd>ChatGPTRun docstring<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun docstring" },
--        { "<Leader>ca", "<Cmd>ChatGPTRun add_tests<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun add_tests" },
--        { "<Leader>co", "<Cmd>ChatGPTRun optimize_code<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun optimize_code" },
--        { "<Leader>cs", "<Cmd>ChatGPTRun summarize<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun summarize" },
--        { "<Leader>cf", "<Cmd>ChatGPTRun fix_bugs<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun fix_bugs" },
--        { "<Leader>cx", "<Cmd>ChatGPTRun explain_code<Cr>", mode = { "n", "v" }, desc = "ChatGPTRun explain_code" },
--        {
--          "<Leader>cr",
--          "<Cmd>ChatGPTRun code_readability_analysis<Cr>",
--          mode = { "n", "v" },
--          desc = "ChatGPTRun code_readability_analysis",
--        },
--      }
--    end,
--    event = "VeryLazy",
--    dependencies = {
--      "MunifTanjim/nui.nvim",
--      "nvim-lua/plenary.nvim",
--      "nvim-telescope/telescope.nvim",
--    },
--  },
--
--  { "stevearc/stickybuf.nvim", cmd = { "PinBuffer", "PinBuftype", "PinFiletype" }, opts = {} },
--
--  {
--    "willothy/flatten.nvim",
--    opts = {
--      window = {
--        open = "tab",
--      },
--      one_per = { kitty = false, wezterm = false },
--      block_for = {
--        gitcommit = true,
--        gitrebase = true,
--      },
--      post_open = function(bufnr, winnr, ft, is_blocking)
--        vim.w[winnr].is_remote = true
--        if is_blocking then
--          vim.bo[bufnr].bufhidden = "wipe"
--          local has_stickybuf, stickybuf = pcall(require, "stickybuf")
--          if has_stickybuf then stickybuf.pin(winnr) end
--          vim.api.nvim_create_autocmd("BufHidden", {
--            desc = "Close window when buffer is hidden",
--            callback = function()
--              if vim.api.nvim_win_is_valid(winnr) then vim.api.nvim_win_close(winnr, true) end
--            end,
--            buffer = bufnr,
--            once = true,
--          })
--        end
--      end,
--    },
--  },
--  {
--    "AckslD/nvim-FeMaco.lua",
--    cmd = "FeMaco",
--    config = true,
--  },
--  {
--    "ojroques/nvim-osc52",
--    -- Only change the clipboard if we're in a SSH session
--    cond = os.getenv("SSH_CLIENT") ~= nil and (os.getenv("TMUX") ~= nil or vim.fn.has("nvim-0.10") == 0),
--    config = function()
--      local osc52 = require("osc52")
--      local function copy(lines, _) osc52.copy(table.concat(lines, "\n")) end
--
--      local function paste() return { vim.fn.split(vim.fn.getreg(""), "\n"), vim.fn.getregtype("") } end
--
--      vim.g.clipboard = {
--        name = "osc52",
--        copy = { ["+"] = copy, ["*"] = copy },
--        paste = { ["+"] = paste, ["*"] = paste },
--      }
--    end,
--  },
--  {
--    "sindrets/diffview.nvim",
--    cmd = {
--      "DiffviewOpen",
--      "DiffviewClose",
--      "DiffviewToggleFiles",
--      "DiffviewFocusFiles",
--      "DiffviewRefresh",
--    },
--    config = "plugins.diffview",
--  },
--  { "folke/flash.nvim", config = "plugins.flash" },
--  {
--    "akinsho/git-conflict.nvim",
--    config = "plugins.git-conflict",
--    cmd = {
--      "GitConflictChooseOurs",
--      "GitConflictChooseTheirs",
--      "GitConflictChooseBoth",
--      "GitConflictChooseNone",
--      "GitConflictNextConflict",
--      "GitConflictPrevConflict",
--    },
--  },
--  { "echasnovski/mini.pairs", event = "VeryLazy", opts = {} },
--  {
--    "echasnovski/mini.move",
--    allow_in_vscode = true,
--    keys = {
--      { "<C-h>", nil, mode = { "n", "v" } },
--      { "<C-j>", nil, mode = { "n", "v" } },
--      { "<C-k>", nil, mode = { "n", "v" } },
--      { "<C-l>", nil, mode = { "n", "v" } },
--    },
--    opts = {
--      mappings = {
--        left = "<C-h>",
--        right = "<C-l>",
--        down = "<C-j>",
--        up = "<C-k>",
--        line_left = "<C-h>",
--        line_right = "<C-l>",
--        line_down = "<C-j>",
--        line_up = "<C-k>",
--      },
--    },
--    config = function(_, opts) require("mini.move").setup(opts) end,
--  },
--  {
--    "kevinhwang91/nvim-hlslens",
--    config = function()
--      require("hlslens").setup({
--        calm_down = false,
--        nearest_only = false,
--        nearest_float_when = "never",
--      })
--    end,
--    keys = {
--      { "*", "*<Cmd>lua require('hlslens').start()<CR>", silent = true },
--      { "#", "#<Cmd>lua require('hlslens').start()<CR>", silent = true },
--      { "g*", "g*<Cmd>lua require('hlslens').start()<CR>", silent = true },
--      { "g#", "g#<Cmd>lua require('hlslens').start()<CR>", silent = true },
--      {
--        "n",
--        "<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>",
--      },
--      {
--        "N",
--        "<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>",
--      },
--    },
--  },
--  {
--    "TwIStOy/nvim-lastplace",
--    event = "BufReadPre",
--    opts = {
--      lastplace_ignore_buftype = { "quickfix", "nofile", "help", "alpha" },
--      lastplace_ignore_filetype = {
--        "gitcommit",
--        "gitrebase",
--        "svn",
--        "hgcommit",
--      },
--      lastplace_open_folds = true,
--    },
--  },
--  {
--    "ghostbuster91/nvim-next",
--    event = "VeryLazy",
--    config = function()
--      local next = require("nvim-next")
--      local builtins = require("nvim-next.builtins")
--      local integrations = require("nvim-next.integrations")
--
--      next.setup({
--        default_mappings = {
--          repeat_style = "original",
--        },
--        items = {
--          builtins.f,
--          builtins.t,
--        },
--      })
--
--      -- Diagnostic
--      local diag = integrations.diagnostic()
--      vim.keymap.set("n", "[d", diag.goto_prev(), { desc = "Previous diagnostic" })
--      vim.keymap.set("n", "]d", diag.goto_next(), { desc = "Next diagnostic" })
--
--      -- Quickfix
--      local nqf = integrations.quickfix()
--      vim.keymap.set("n", "[q", nqf.cprevious, { desc = "Previous quickfix item" })
--      vim.keymap.set("n", "]q", nqf.cnext, { desc = "Next quickfix item" })
--    end,
--  },
--  {
--    "tpope/vim-sleuth",
--    event = "VeryLazy",
--  },
--  { "chrisbra/csv.vim", ft = "csv" },
--  { "RaafatTurki/hex.nvim", opts = {} },
--  { "fladson/vim-kitty", event = { "BufReadPre kitty.conf" } },
--  {
--    "AckslD/nvim-neoclip.lua",
--    dependencies = {
--      "kkharji/sqlite.lua",
--      "nvim-telescope/telescope.nvim",
--    },
--    config = function()
--      require("neoclip").setup({
--        enable_persistent_history = true,
--        db_path = vim.fn.stdpath("data") .. "/databases/neoclip.sqlite3",
--      })
--      require("telescope").load_extension("neoclip")
--    end,
--  },
--  {
--    "yorickpeterse/nvim-pqf",
--    lazy = true,
--    opts = {
--      show_multiple_lines = true,
--    },
--    config = true,
--    main = "pqf",
--  },
--  {
--    "mbbill/undotree",
--    lazy = false,
--    cmd = "UndotreeToggle",
--    keys = {
--      { "<Leader>uu", "<cmd>UndotreeToggle<CR>", desc = "Undotree Toggle" },
--    },
--  },
--  { "folke/twilight.nvim", opts = {} },
--  {
--    "nvim-neorg/neorg",
--    dependencies = { "nvim-lua/plenary.nvim", "nvim-treesitter/nvim-treesitter", "jbyuki/venn.nvim" },
--    build = ":Neorg sync-parsers",
--    keys = {
--      { "<CR>", ":VBox<CR>", mode = "v" },
--    },
--    ft = "norg",
--    cmd = "Neorg",
--    opts = {
--      load = {
--        ["core.defaults"] = {}, -- Loads default behaviour
--        ["core.concealer"] = { -- Adds pretty icons to your documents
--          config = {
--            icons = {
--              todo = {
--                undone = {
--                  icon = " ",
--                },
--              },
--            },
--          },
--        },
--        ["core.completion"] = {
--          config = {
--            engine = "nvim-cmp",
--          },
--        },
--        -- This is deleting the non-empty contents of files
--        -- ["core.esupports.metagen"] = {
--        --   config = {
--        --     type = "auto",
--        --   },
--        -- },
--        ["core.presenter"] = {
--          config = {
--            zen_mode = "zen-mode",
--          },
--        },
--        ["core.keybinds"] = {
--          config = {
--            hook = function(keybinds)
--              keybinds.unmap("norg", "n", "<CR>")
--
--              keybinds.unmap("presenter", "n", "l")
--              keybinds.unmap("presenter", "n", "h")
--              keybinds.unmap("presenter", "n", "<CR>")
--              keybinds.unmap("presenter", "n", "q")
--
--              -- Unmaps any Neorg key from the `norg` mode
--              keybinds.remap_event("presenter", "n", "<Right>", "core.presenter.next_page")
--              keybinds.remap_event("presenter", "n", "<C-j>", "core.presenter.next_page")
--              keybinds.remap_event("presenter", "n", "<Left>", "core.presenter.previous_page")
--              keybinds.remap_event("presenter", "n", "<C-k>", "core.presenter.previous_page")
--              keybinds.remap_event("presenter", "n", "<Down>", "core.presenter.close")
--              keybinds.map("norg", "n", "<Up>", "<CMD>Neorg presenter start<CR>")
--            end,
--          },
--        },
--      },
--    },
--    config = function(_, opts)
--      local neorg = require("neorg")
--      neorg.setup(opts)
--
--      local utils = require("meg.utils")
--
--      utils.p("quick_action", function(quick_action)
--        quick_action.add("menu", {
--          name = "Toggle todo status",
--          condition = function()
--            if vim.bo.filetype ~= "norg" then return false end
--            local lnum = vim.api.nvim_win_get_cursor(0)[1] - 1
--            local todo_module = neorg.modules.get_module("core.qol.todo_items")
--            local item = todo_module and todo_module.get_todo_item_from_cursor(0, lnum)
--            local row = item and item:start()
--            return row == lnum
--          end,
--          action = function() vim.cmd("Neorg keybind norg core.qol.todo_items.todo.task_cycle") end,
--        })
--      end)
--    end,
--  },
--
--  {
--    "mhanberg/output-panel.nvim",
--    keys = {
--      { "<leader>uo", "<cmd>OutputPanel<cr>", desc = "Toggle LSP output" },
--    },
--    config = true,
--  },
--  {
--    "pwntester/octo.nvim",
--    cmd = "Octo",
--    dependencies = {
--      "nvim-lua/plenary.nvim",
--      "nvim-telescope/telescope.nvim",
--      "nvim-tree/nvim-web-devicons",
--    },
--    config = function()
--      require("octo").setup({ enable_builtin = true })
--      vim.treesitter.language.register("markdown", "octo")
--    end,
--    keys = {
--      { "<Leader>o", "<cmd>Octo<CR>", desc = "Octo" },
--    },
--  },
--
--  {
--    "roberte777/keep-it-secret.nvim",
--    eager = true,
--    opts = {
--      wildcards = { ".*(.env)$", ".*(.secret)$" },
--      enabled = false,
--    },
--  },
--
--  {
--    "epwalsh/obsidian.nvim",
--    dependencies = {
--      "nvim-lua/plenary.nvim",
--      "hrsh7th/nvim-cmp",
--      "nvim-telescope/telescope.nvim",
--      "nvim-treesitter/nvim-treesitter",
--      -- "preservim/vim-markdown",
--    },
--
--    lazy = true,
--    event = {
--      "BufReadPre " .. vim.fn.expand("~") .. "/repos/second-brain/**.md",
--      "BufNewFile " .. vim.fn.expand("~") .. "/repos/second-brain/**.md",
--    },
--    commands = {
--      "ObsidianOpen",
--      "ObsidianNew",
--      "ObsidianQuickSwitch",
--      "ObsidianFollowLink",
--      "ObsidianBacklinks",
--      "ObsidianToday",
--      "ObsidianYesterday",
--      "ObsidianTemplate",
--      "ObsidianSearch",
--      "ObsidianLink",
--      "ObsidianLinkNew",
--    },
--
--    opts = {
--      dir = "~/repos/second-brain", -- no need to call 'vim.fn.expand' here
--      completion = { nvim_cmp = true },
--
--      daily_notes = {
--        folder = "Calendar 🗓️/Days 🌄",
--        -- Optional, if you want to change the date format for the ID of daily notes.
--        -- date_format = "%Y-%m-%d",
--        -- Optional, if you want to change the date format of the default alias of daily notes.
--        -- alias_format = "%B %-d, %Y",
--      },
--
--      -- Optional, alternatively you can customize the frontmatter data.
--      note_frontmatter_func = function(note)
--        -- This is equivalent to the default frontmatter function.
--        local out = { id = note.id, aliases = note.aliases, tags = note.tags }
--        -- `note.metadata` contains any manually added fields in the frontmatter.
--        -- So here we just make sure those fields are kept in the frontmatter.
--        if note.metadata ~= nil and require("obsidian").util.table_length(note.metadata) > 0 then
--          for k, v in pairs(note.metadata) do
--            out[k] = v
--          end
--        end
--        return out
--      end,
--
--      -- Optional, for templates (see below).
--      templates = {
--        subdir = "templates",
--        date_format = "%Y-%m-%d-%a",
--        time_format = "%H:%M",
--      },
--
--      follow_url_func = function(url) vim.fn.jobstart({ "open", url }) end,
--
--      -- Optional, set to true if you use the Obsidian Advanced URI plugin.
--      -- https://github.com/Vinzent03/obsidian-advanced-uri
--      use_advanced_uri = true,
--
--      -- Optional, set to true to force ':ObsidianOpen' to bring the app to the foreground.
--      open_app_foreground = true,
--    },
--
--    -- mappings = {
--    --   ["gf"] = require("obsidian.mapping").gf_passthrough(),
--    -- },
--
--    config = function(_, opts)
--      require("obsidian").setup(opts)
--      vim.keymap.set("n", "gd", function()
--        if require("obsidian").util.cursor_on_markdown_link() then
--          return "<cmd>ObsidianFollowLink<CR>"
--        else
--          return "gd"
--        end
--      end, { noremap = false, expr = true })
--    end,
--  },
--  {
--    "nvim-neotest/neotest",
--    dependencies = {
--      "nvim-neotest/neotest-python",
--      "nvim-neotest/neotest-plenary",
--      "nvim-neotest/neotest-jest",
--      "nvim-neotest/neotest-go",
--      "olimorris/neotest-rspec",
--      "stevearc/overseer.nvim",
--      "nvim-lua/plenary.nvim",
--    },
--    keys = {
--      { "<leader>ta", "<cmd>lua require('neotest').run.attach()<cr>", desc = "Attach to the nearest test" },
--      { "<leader>tl", "<cmd>lua require('neotest').run.run_last()<cr>", desc = "Toggle Test Summary" },
--      { "<leader>to", "<cmd>lua require('neotest').output_panel.toggle()<cr>", desc = "Toggle Test Output Panel" },
--      { "<leader>tp", "<cmd>lua require('neotest').run.stop()<cr>", desc = "Stop the nearest test" },
--      { "<leader>ts", "<cmd>lua require('neotest').summary.toggle()<cr>", desc = "Toggle Test Summary" },
--      { "<leader>tt", "<cmd>lua require('neotest').run.run()<cr>", desc = "Run the nearest test" },
--      {
--        "<leader>tT",
--        "<cmd>lua require('neotest').run.run(vim.fn.expand('%'))<cr>",
--        desc = "Run test the current file",
--      },
--    },
--    config = function()
--      local neotest = require("neotest")
--      -- require("neotest.logging"):set_level("trace")
--      neotest.setup({
--        adapters = {
--          require("neotest-rspec"),
--          require("neotest-python")({
--            dap = { justMyCode = false },
--          }),
--          require("neotest-plenary"),
--          require("neotest-go"),
--          require("neotest-jest")({
--            cwd = require("neotest-jest").root,
--          }),
--        },
--        discovery = {
--          enabled = false,
--        },
--        consumers = {
--          overseer = require("neotest.consumers.overseer"),
--        },
--        summary = {
--          mappings = {
--            attach = "a",
--            expand = "l",
--            expand_all = "L",
--            jumpto = "gf",
--            output = "o",
--            run = "<C-r>",
--            short = "p",
--            stop = "u",
--          },
--        },
--        icons = {
--          passed = " ",
--          running = " ",
--          failed = " ",
--          unknown = " ",
--          running_animated = vim.tbl_map(
--            function(s) return s .. " " end,
--            { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" }
--          ),
--        },
--        diagnostic = {
--          enabled = true,
--        },
--        output = {
--          enabled = true,
--          open_on_run = false,
--        },
--        status = {
--          enabled = true,
--        },
--      })
--      vim.keymap.set("n", "<leader>tn", function() neotest.run.run({}) end)
--      vim.keymap.set("n", "<leader>tt", function() neotest.run.run({ vim.api.nvim_buf_get_name(0) }) end)
--      vim.keymap.set("n", "<leader>ta", function()
--        for _, adapter_id in ipairs(neotest.run.adapters()) do
--          neotest.run.run({ suite = true, adapter = adapter_id })
--        end
--      end)
--      vim.keymap.set("n", "<leader>tl", function() neotest.run.run_last() end)
--      vim.keymap.set("n", "<leader>td", function() neotest.run.run({ strategy = "dap" }) end)
--      vim.keymap.set("n", "<leader>tp", function() neotest.summary.toggle() end)
--      vim.keymap.set("n", "<leader>to", function() neotest.output.open({ short = true }) end)
--    end,
--  },
--  { "tpope/vim-abolish", keys = { { "cr", "<Plug>(abolish-coerce-word)", mode = "n" } } },
--  "gioele/vim-autoswap",
--  { "tpope/vim-eunuch", ft = { "sh" }, cmd = { "Remove", "Delete" } },
--  {
--    "kylechui/nvim-surround",
--    version = "*",
--    event = "BufReadPost",
--    config = function() require("nvim-surround").setup({}) end,
--  },
--  {
--    "uga-rosa/ccc.nvim",
--    cmd = { "CccPick" },
--    ft = { "html", "css", "sass", "less", "javascript", "typescript", "javascriptreact", "typescriptreact" },
--    config = "plugins.ccc",
--  },
--  {
--    "jedrzejboczar/possession.nvim",
--    cmd = {
--      "SSave",
--      "SLoad",
--      "SDelete",
--      "SList",
--    },
--    dependencies = { "nvim-lua/plenary.nvim" },
--    eager = true,
--    opts = {
--      silent = true,
--      commands = {
--        save = "SSave",
--        load = "SLoad",
--        delete = "SDelete",
--        list = "SList",
--      },
--    },
--    config = true,
--  },
--  {
--    "TwIStOy/project.nvim",
--    event = { "BufReadPost", "BufNewFile" },
--    cmd = { "PickRecentProject" },
--    opts = {
--      detection_methods = { "pattern" },
--      patterns = {
--        "BLADE_ROOT",
--        "blast.json",
--        ".git",
--        "_darcs",
--        ".hg",
--        ".bzr",
--        ".svn",
--        "Makefile",
--      },
--      exclude_dirs = {
--        "~/.cargo/*",
--      },
--      silent_chdir = false,
--      open_callback = function()
--        vim.schedule(function()
--          if vim.fn.argc() == 0 and vim.o.lines >= 36 and vim.o.columns >= 80 then require("alpha").redraw() end
--        end)
--      end,
--    },
--    dependencies = {
--      "nvim-telescope/telescope.nvim",
--    },
--    config = function(_, opts)
--      require("project_nvim").setup(opts)
--
--      vim.api.nvim_create_user_command(
--        "PickRecentProject",
--        function()
--          require("telescope").extensions.projects.projects({
--            layout_strategy = "center",
--            sorting_strategy = "ascending",
--            layout_config = {
--              anchor = "N",
--              width = 0.5,
--              prompt_position = "top",
--              height = 0.5,
--            },
--            border = true,
--            results_title = false,
--            borderchars = {
--              prompt = { "─", "│", " ", "│", "╭", "╮", "│", "│" },
--              results = {
--                "─",
--                "│",
--                "─",
--                "│",
--                "├",
--                "┤",
--                "╯",
--                "╰",
--              },
--              preview = {
--                "─",
--                "│",
--                "─",
--                "│",
--                "╭",
--                "╮",
--                "╯",
--                "╰",
--              },
--            },
--          })
--        end,
--        {}
--      )
--    end,
--  },
--  {
--    "m4xshen/smartcolumn.nvim",
--    opts = {
--      colorcolumn = "80",
--      disabled_filetypes = {
--        "help",
--        "NvimTree",
--        "lazy",
--        "mason",
--        "help",
--        "alpha",
--      },
--    },
--    event = { "BufReadPre", "BufNewFile" },
--    config = true,
--  },
--  { "sQVe/sort.nvim", cmd = { "Sort" }, config = true },
--  "wellle/targets.vim",
--  {
--    "lambdalisue/suda.vim",
--    cmd = {
--      "SudaRead",
--      "SudaWrite",
--    },
--    init = function() vim.g["suda#nopass"] = 1 end,
--  },
--  {
--    "junegunn/vim-easy-align",
--    cmd = { "EasyAlign" },
--    dependencies = {
--      {
--        "godlygeek/tabular",
--        cmd = { "Tabularize" },
--      },
--    },
--    keys = {
--      { "<leader>ta", "<cmd>EasyAlign<CR>", desc = "easy-align" },
--      { "<leader>ta", "<cmd>EasyAlign<CR>", mode = "x", desc = "easy-align" },
--    },
--  },
--  {
--    "osyo-manga/vim-jplus",
--    allow_in_vscode = true,
--    event = "BufReadPost",
--    keys = { { "J", "<Plug>(jplus)", mode = { "n", "v" }, noremap = false } },
--  },
--  { "tpope/vim-endwise", event = "InsertEnter" },
--  {
--    "andymass/vim-matchup",
--    enabled = true,
--    event = { "BufReadPost", "BufAdd", "BufNewFile" },
--    init = function() -- code to run before plugin loaded
--      vim.g.matchup_surround_enabled = 1
--      vim.g.matchup_matchparen_timeout = 100
--      vim.g.matchup_matchparen_deferred = 1
--      vim.g.matchup_matchparen_deferred_show_delay = 50
--      vim.g.matchup_matchparen_deferred_hide_delay = 300
--      vim.g.matchup_matchparen_hi_surround_always = 2
--      vim.g.matchup_matchparen_offscreen = {
--        method = "status_manual",
--      }
--      vim.g.matchup_delim_start_plaintext = 1
--      vim.g.matchup_motion_override_Npercent = 0
--      vim.g.matchup_motion_cursor_end = 0
--      vim.g.matchup_mappings_enabled = 0
--    end,
--    config = function() -- code to run after plugin loaded
--      vim.cmd([[hi! link MatchWord Underlined]])
--
--      vim.cmd([[
--        aug Matchup
--        au!
--        au TermOpen * let [b:matchup_matchparen_enabled, b:matchup_matchparen_fallback] = [0, 0]
--        aug END
--        ]])
--
--      vim.api.nvim_set_keymap("n", "%", "<plug>(matchup-%)", { silent = true })
--      vim.api.nvim_set_keymap("x", "%", "<plug>(matchup-%)", { silent = true })
--      vim.api.nvim_set_keymap("o", "%", "<plug>(matchup-%)", { silent = true })
--    end,
--  },
--  {
--    "dhruvasagar/vim-table-mode",
--    lazy = true,
--    ft = { "markdown", "org" },
--    cmd = { "TableModeEnable", "TableModeDisable" },
--  },
--  {
--    "vuki656/package-info.nvim",
--    dependencies = { "MunifTanjim/nui.nvim" },
--    ft = { "json" },
--    opts = {
--      package_manager = "pnpm",
--      colors = {
--        -- TODO: add to catppuccin
--        up_to_date = "#B1D99C", -- Text color for up to date dependency virtual text
--        outdated = "#EAAC86", -- Text color for outdated dependency virtual text
--      },
--      autostart = true,
--      hide_up_to_date = true,
--      hide_unstable_versions = false,
--    },
--    keys = function()
--      require("which-key").register({ n = { name = "+PackageInfo" } }, { prefix = "<leader>" })
--      local function map(key, cmd, desc)
--        vim.keymap.set({ "n" }, "<LEADER>n" .. key, cmd, { desc = desc, silent = true, noremap = true })
--      end
--      local pi = require("package-info")
--      map("s", pi.show, "Show package info")
--      map("h", pi.hide, "Hide package info")
--      map("n", pi.toggle, "Toggle package info")
--      map("u", pi.update, "Update package")
--      map("d", pi.delete, "Delete package")
--      map("i", pi.install, "Install package")
--      map("v", pi.change_version, "Change package version")
--    end,
--  },
--  {
--    "stevearc/oil.nvim",
--    dependencies = {
--      "nvim-tree/nvim-web-devicons",
--    },
--    init = function()
--      local netrw_bufname
--
--      pcall(vim.api.nvim_clear_autocmds, { group = "FileExplorer" })
--
--      vim.api.nvim_create_autocmd("VimEnter", {
--        pattern = "*",
--        once = true,
--        callback = function() pcall(vim.api.nvim_clear_autocmds, { group = "FileExplorer" }) end,
--      })
--
--      vim.api.nvim_create_autocmd("BufEnter", {
--        group = vim.api.nvim_create_augroup("oil.nvim", { clear = true }),
--        pattern = "*",
--        callback = function()
--          vim.schedule(function()
--            if vim.bo[0].filetype == "netrw" then return end
--            local bufname = vim.api.nvim_buf_get_name(0)
--            if vim.fn.isdirectory(bufname) == 0 then
--              _, netrw_bufname = pcall(vim.fn.expand, "#:p:h")
--              return
--            end
--
--            -- prevents reopening of file-browser if exiting without selecting a file
--            if netrw_bufname == bufname then
--              netrw_bufname = nil
--              return
--            else
--              netrw_bufname = bufname
--            end
--
--            -- ensure no buffers remain with the directory name
--            vim.api.nvim_buf_set_option(0, "bufhidden", "wipe")
--
--            require("oil").open_float()
--          end)
--        end,
--        desc = "oil.nvim replacement for netrw",
--      })
--    end,
--    config = "plugins.oil",
--  },
--  {
--    "nvim-tree/nvim-tree.lua",
--    enabled = false,
--    opts = {
--      hijack_cursor = true,
--      sync_root_with_cwd = true,
--      respect_buf_cwd = true,
--      update_focused_file = {
--        enable = true,
--        update_root = false,
--      },
--      view = {
--        adaptive_size = true,
--      },
--      renderer = {
--        full_name = true,
--        group_empty = true,
--        symlink_destination = false,
--        indent_markers = {
--          enable = true,
--        },
--        icons = {
--          git_placement = "signcolumn",
--          show = {
--            file = true,
--            folder = true,
--            folder_arrow = true,
--            git = true,
--          },
--        },
--      },
--      diagnostics = {
--        enable = true,
--        show_on_dirs = true,
--      },
--      filters = {
--        custom = {
--          "^.git$",
--        },
--      },
--    },
--    init = function()
--      vim.g.loaded_netrw = 1
--      vim.g.loaded_netrwPlugin = 1
--      vim.opt.termguicolors = true
--    end,
--    config = function(_, opts) require("nvim-tree").setup(opts) end,
--  },
--  {
--    "nvim-treesitter/nvim-treesitter",
--    dependencies = {
--      "windwp/nvim-ts-autotag",
--      "nvim-treesitter/nvim-treesitter-textobjects",
--      "JoosepAlviste/nvim-ts-context-commentstring",
--    },
--    event = "User BaseFile",
--    cmd = {
--      "TSBufDisable",
--      "TSBufEnable",
--      "TSBufToggle",
--      "TSDisable",
--      "TSEnable",
--      "TSToggle",
--      "TSInstall",
--      "TSInstallInfo",
--      "TSInstallSync",
--      "TSModuleInfo",
--      "TSUninstall",
--      "TSUpdate",
--      "TSUpdateSync",
--    },
--    build = ":TSUpdate",
--    config = "plugins.treesitter",
--  },
--  { dir = "meg/colorschemes", priority = 90, config = "colorschemes", eager = true },
--  { dir = "meg/client", priority = 95, config = "client", eager = true },
--  { "Bekaboo/dropbar.nvim", event = "VeryLazy", config = "plugins.dropbar" },
--  { "wakatime/vim-wakatime", priority = 90, eager = true },
--  { "tenxsoydev/nx.nvim", priority = 100, config = function() _G.nx = require("nx") end, eager = true },
--  { "famiu/bufdelete.nvim", lazy = true },
--  {
--    "L3MON4D3/LuaSnip",
--    build = "make install_jsregexp",
--    allow_in_vscode = true,
--    event = { "InsertEnter" },
--    config = "plugins.luasnip",
--    keys = {
--      {
--        "<C-e>",
--        function()
--          local ls = require("luasnip")
--          if ls.choice_active() then ls.change_choice(1) end
--        end,
--        mode = { "i", "s", "n", "v" },
--      },
--      {
--        "<C-b>",
--        function()
--          local ls = require("luasnip")
--          if ls.jumpable(-1) then ls.jumpable(-1) end
--        end,
--        mode = { "i", "s", "n", "v" },
--      },
--      {
--        "<C-f>",
--        function()
--          local ls = require("luasnip")
--          if ls.expand_or_jumpable() then ls.expand_or_jump() end
--        end,
--        mode = { "i", "s", "n", "v" },
--      },
--    },
--  },
--  {
--    "hrsh7th/nvim-cmp",
--    event = "InsertEnter",
--    dependencies = {
--      "onsails/lspkind.nvim",
--      "lukas-reineke/cmp-under-comparator",
--      "saadparwaiz1/cmp_luasnip",
--      "L3MON4D3/LuaSnip",
--      "hrsh7th/cmp-cmdline",
--      "dmitmel/cmp-cmdline-history",
--      "hrsh7th/cmp-nvim-lsp",
--      "hrsh7th/cmp-calc",
--      "hrsh7th/cmp-emoji",
--      "dmitmel/cmp-digraphs",
--      "f3fora/cmp-spell",
--      "hrsh7th/cmp-buffer",
--      "hrsh7th/cmp-path",
--      "rafamadriz/friendly-snippets",
--      "kdheepak/cmp-latex-symbols",
--      {
--        "paopaol/cmp-doxygen",
--        dependencies = {
--          "nvim-treesitter/nvim-treesitter",
--          "nvim-treesitter/nvim-treesitter-textobjects",
--        },
--      },
--      -- "zbirenbaum/copilot-cmp",
--    },
--    config = "plugins.cmp",
--  },
--  {
--    "akinsho/flutter-tools.nvim",
--    dependencies = {
--      "nvim-lua/plenary.nvim",
--      "stevearc/dressing.nvim",
--      "nvim-telescope/telescope.nvim",
--    },
--  },
--  {
--    "TobinPalmer/rayso.nvim",
--    cmd = "Rayso",
--    opts = {
--      base_url = "https://ray.so/", -- Default URL
--      open_cmd = "Arc", -- On MacOS, will open with open -a firefox.app. Other OS's are untested.
--      options = {
--        background = true, -- If the screenshot should have a background.
--        dark_mode = true, -- If the screenshot should be in dark mode.
--        logging_path = "", -- Path to create a log file in.
--        logging_file = "rayso", -- Name of log file, will be a markdown file, ex rayso.md.
--        logging_enabled = false, -- If you enable the logging file.
--        padding = 32, -- The default padding that the screenshot will have.
--        theme = "raindrop", -- Theme
--      },
--    },
--    keys = {
--      { "<leader>rs", "<cmd>Rayso<cr>", desc = "Share with Rayso" },
--    },
--  },
--  {
--    "ThePrimeagen/refactoring.nvim",
--    dependencies = {
--      { "nvim-lua/plenary.nvim" },
--      { "nvim-treesitter/nvim-treesitter" },
--    },
--    opts = true,
--    keys = {
--      -- Remaps for the refactoring operations currently offered by the plugin
--      { "v", "<leader>re", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function')<CR>]] },
--      { "v", "<leader>rf", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function To File')<CR>]] },
--      { "v", "<leader>rv", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Variable')<CR>]] },
--      { "v", "<leader>ri", [[ <Esc><Cmd>lua require('refactoring').refactor('Inline Variable')<CR>]] },
--
--      -- Extract block doesn't need visual mode
--      { "n", "<leader>rb", [[ <Cmd>lua require('refactoring').refactor('Extract Block')<CR>]] },
--      { "n", "<leader>rbf", [[ <Cmd>lua require('refactoring').refactor('Extract Block To File')<CR>]] },
--
--      -- Inline variable can also pick up the identifier currently under the cursor without visual mode
--      { "n", "<leader>ri", [[ <Cmd>lua require('refactoring').refactor('Inline Variable')<CR>]] },
--    },
--  },
--  {
--    "joshmedeski/telescope-smart-goto.nvim",
--    dependencies = {
--      "nvim-telescope/telescope.nvim",
--      "ThePrimeagen/harpoon",
--    },
--  },
--  {
--    "stevearc/dressing.nvim",
--    config = "plugins.dressing",
--  },
--  {
--    "NeogitOrg/neogit",
--    dependencies = {
--      "nvim-lua/plenary.nvim",
--      "sindrets/diffview.nvim",
--    },
--    cmd = "Neogit",
--    opts = {
--      signs = {
--        hunk = { "", "" },
--        item = { "", "" },
--        section = { "", "" },
--      },
--      integrations = {
--        diffview = true,
--      },
--    },
--  },
--  {
--    "lmburns/lf.nvim",
--    cmd = "Lf",
--    dependencies = {
--      "akinsho/toggleterm.nvim",
--      "nvim-lua/plenary.nvim",
--    },
--    opts = {
--      border = "single",
--      escape_quit = true,
--      highlights = { NormalFloat = { guibg = "NONE" } },
--      winblend = 0,
--    },
--    keys = {
--      { "<leader>ff", "<cmd>Lf<cr>", desc = "Lf" },
--    },
--  },
--  { "tzachar/highlight-undo.nvim", opts = {} },
--  {
--    "AckslD/nvim-neoclip.lua",
--    dependencies = { "kkharji/sqlite.lua" },
--    keys = {
--      { "<leader>P", "<cmd>Telescope neoclip<cr>", desc = "Neoclip" },
--    },
--    opts = {
--      history = 1000,
--      enable_persistent_history = true,
--      length_limit = 1048576,
--      continuous_sync = false,
--      db_path = vim.fn.stdpath("data") .. "/databases/neoclip.sqlite3",
--      filter = nil,
--      preview = true,
--      prompt = nil,
--      default_register = '"',
--      default_register_macros = "q",
--      enable_macro_history = true,
--      content_spec_column = false,
--      disable_keycodes_parsing = false,
--      on_select = {
--        move_to_front = false,
--        close_telescope = true,
--      },
--      on_paste = {
--        set_reg = false,
--        move_to_front = false,
--        close_telescope = true,
--      },
--      on_replay = {
--        set_reg = false,
--        move_to_front = false,
--        close_telescope = true,
--      },
--      on_custom_action = {
--        close_telescope = true,
--      },
--      keys = {
--        telescope = {
--          i = {
--            select = "<cr>",
--            paste = "<c-p>",
--            paste_behind = "<c-k>",
--            replay = "<c-q>", -- replay a macro
--            delete = "<c-d>", -- delete an entry
--            edit = "<c-e>", -- edit an entry
--            custom = {},
--          },
--          n = {
--            select = "<cr>",
--            paste = "p",
--            --- It is possible to map to more than one key.
--            -- paste = { 'p', '<c-p>' },
--            paste_behind = "P",
--            replay = "q",
--            delete = "d",
--            edit = "e",
--            custom = {},
--          },
--        },
--      },
--    },
--  },
--  {
--    "tpope/vim-fugitive",
--    dependencies = {
--      "tpope/vim-rhubarb",
--      "rbong/vim-flog",
--    },
--    cmd = { "GitHistory", "Git", "GBrowse", "Gwrite", "Flog", "Flogsplit" },
--    keys = {
--      { "<leader>gg", "<cmd>Flog -all<CR>", { mode = "n", desc = "[G]it [G]raph" } },
--      { "<leader>gh", "<cmd>GitHistory<CR>", { mode = "n", desc = "[G]it [H]istory" } },
--      { "<leader>gb", "<cmd>Git blame<CR>", { mode = "n", desc = "[G]it [B]lame" } },
--      { "<leader>gc", "<cmd>GBrowse!<CR>", { mode = "n", desc = "[G]it [C]opy link" } },
--      { "<leader>gc", ":GBrowse!<CR>", { mode = "v", desc = "[G]it [C]opy link" } },
--    },
--    config = function() vim.cmd("command! GitHistory Git! log -- %") end,
--  },
--  {
--    "3rd/image.nvim",
--    ft = { "markdown", "norg", "oil" },
--    build = function()
--      local has_magic = pcall(require, "magick")
--      if not has_magick and vim.fn.executable("luarocks") == 1 then
--        if is_mac then
--          vim.fn.system("luarocks --lua-dir=$(brew --prefix)/opt/lua@5.1 --lua-version=5.1 install magick")
--        else
--          vim.fn.system("luarocks --local --lua-version=5.1 install magick")
--        end
--        if vim.v.shell_error ~= 0 then vim.notify("Error installing magick with luarocks", vim.log.levels.WARN) end
--      end
--    end,
--    opts = {
--      editor_only_render_when_focused = true,
--      tmux_show_only_in_active_window = true,
--    },
--    config = function(_, opts)
--      local has_magic = pcall(require, "magick")
--      if has_magick then require("image").setup(opts) end
--    end,
--  },
--  {
--    "dnlhc/glance.nvim",
--    cmd = { "Glance" },
--    config = "plugins.glance",
--  },
--  {
--    "onsails/lspkind.nvim",
--    dependencies = {
--      "nvim-tree/nvim-web-devicons",
--    },
--    config = "plugins.lspkind",
--  },
--  {
--    "nvimdev/lspsaga.nvim",
--    event = "LspAttach",
--    dependencies = {
--      "nvim-tree/nvim-web-devicons",
--      "nvim-treesitter/nvim-treesitter",
--    },
--    config = function()
--      require("lspsaga").setup({
--        code_action = {
--          num_shortcut = true,
--          show_server_name = true,
--          extend_gitsigns = false,
--          keys = { quit = { "q", "<Esc>" }, exec = "<CR>" },
--        },
--        lightbulb = { enable = false },
--        symbol_in_winbar = { enable = false },
--        ui = {},
--      })
--    end,
--  },
--  {
--    "TwIStOy/neodim",
--    event = "LspAttach",
--    config = function()
--      require("neodim").setup({
--        alpha = 0.75,
--        blend_color = "#000000",
--        update_in_insert = { enable = false, delay = 100 },
--        hide = { virtual_text = true, signs = false, underline = false },
--      })
--    end,
--  },
--  {
--    "neovim/nvim-lspconfig",
--    event = { "BufReadPre", "BufNewFile" },
--    config = "plugins.lsp",
--    dependencies = {
--      {
--        { "b0o/SchemaStore.nvim", eager = true },
--        {
--          "williamboman/mason.nvim",
--          cmd = {
--            "Mason",
--            "MasonInstall",
--            "MasonUninstall",
--            "MasonUninstallAll",
--            "MasonLog",
--            "MasonUpdate",
--            "MasonUpdateAll",
--          },
--          opts = {
--            ui = {
--              icons = {
--                package_installed = "✓",
--                package_uninstalled = "✗",
--                package_pending = "⟳",
--              },
--            },
--          },
--          build = ":MasonUpdate",
--        },
--      },
--    },
--  },
--  { "williamboman/mason-lspconfig", cmd = { "LspInstall", "LspUninstall" } },
--  { "stevearc/flow-coverage.nvim", ft = { "javascript", "javascript.jsx", "javascriptreact" } },
--  {
--    "folke/neodev.nvim",
--    ft = "lua",
--    dependencies = {
--      "neovim/nvim-lspconfig",
--    },
--    config = "plugins.neodev",
--  },
--  {
--    "pmizio/typescript-tools.nvim",
--    dependencies = {
--      "nvim-lua/plenary.nvim",
--      "neovim/nvim-lspconfig",
--    },
--    config = "plugins.typescript",
--  },
--  { "simrat39/rust-tools.nvim", lazy = true },
--  {
--    "folke/trouble.nvim",
--    dependencies = { "folke/lsp-colors.nvim" },
--    cmd = { "Trouble", "TroubleClose", "TroubleToggle", "TroubleRefresh" },
--  },
--  {
--    "TwIStOy/right-click.nvim",
--    allow_in_vscode = true,
--    dependencies = {
--      "MunifTanjim/nui.nvim",
--    },
--    config = true,
--  },
--  {
--    "rcarriga/nvim-notify",
--    dependencies = { "nvim-tree/nvim-web-devicons" },
--    opts = {
--      timeout = 3000,
--      stages = "static",
--      fps = 60,
--      max_height = function() return math.floor(vim.o.lines * 0.75) end,
--      max_width = function() return math.floor(vim.o.columns * 0.75) end,
--    },
--    config = true,
--  },
--  {
--    "NvChad/nvim-colorizer.lua",
--    ft = {
--      "vim",
--      "lua",
--    },
--    cmd = {
--      "ColorizerAttachToBuffer",
--      "ColorizerDetachFromBuffer",
--      "ColorizerReloadAllBuffers",
--      "ColorizerToggle",
--    },
--    opts = {
--      filetypes = {
--        "vim",
--        "lua",
--      },
--      user_default_options = {
--        RRGGBB = true,
--        names = false,
--        AARRGGBB = true,
--        mode = "virtualtext",
--      },
--    },
--    config = function(_, opts)
--      require("colorizer").setup(opts)
--      local ft = vim.api.nvim_get_option_value("filetype", {
--        buf = 0,
--      })
--      if ft == "vim" or ft == "lua" then require("colorizer").attach_to_buffer(0) end
--    end,
--  },
--  {
--    "folke/noice.nvim",
--    event = { "ModeChanged", "BufReadPre", "InsertEnter" },
--    dependencies = { "MunifTanjim/nui.nvim", "rcarriga/nvim-notify" },
--    opts = {
--      lsp = {
--        progress = { enabled = false, throttle = 1000 / 10 },
--        override = {
--          ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
--          ["vim.lsp.util.stylize_markdown"] = true,
--          ["cmp.entry.get_documentation"] = true,
--        },
--        signature = {
--          enabled = false,
--          auto_open = {
--            enabled = true,
--            trigger = true,
--            luasnip = true,
--            throttle = 50,
--          },
--        },
--      },
--      views = {
--        cmdline_popup = {
--          position = {
--            row = 7,
--            col = "55%",
--          },
--        },
--        cmdline_popupmenu = {
--          position = {
--            row = 7,
--            col = "55%",
--          },
--        },
--      },
--      messages = { enabled = false },
--      presets = {
--        bottom_search = false,
--        command_palette = true,
--        long_message_to_split = true,
--        inc_rename = false,
--        lsp_doc_border = true,
--      },
--    },
--    config = function(_, opts)
--      vim.defer_fn(function() require("noice").setup(opts) end, 20)
--    end,
--  },
--  { "goolord/alpha-nvim", config = "plugins.alpha", eager = true },
--  { "numToStr/Comment.nvim", event = "VeryLazy", config = "plugins.comment" },
--  { "folke/todo-comments.nvim", event = "VeryLazy", config = "plugins.todo-comments" },
--  { "petertriho/nvim-scrollbar", event = "VeryLazy", config = "plugins.scrollbar" },
--  { "lewis6991/gitsigns.nvim", event = "VeryLazy", config = "plugins.gitsigns" },
--  { "nvim-treesitter/nvim-treesitter-context" },
--  { "zbirenbaum/copilot.lua", config = "plugins.copilot", event = "InsertEnter", cmd = "Copilot" },
--  {
--    "iamcco/markdown-preview.nvim",
--    build = "cd app && npm install",
--    event = "VeryLazy",
--    config = "plugins.markdown-preview",
--    ft = { "markdown" },
--    init = function() vim.g.mkdp_filetypes = { "markdown" } end,
--  },
--  --{ "windwp/nvim-autopairs", event = "VeryLazy", config = "plugins.autopairs" },
--  {
--    "altermo/ultimate-autopair.nvim",
--    event = { "InsertEnter", "CmdlineEnter" },
--    opts = {
--      tabout = {
--        enable = true,
--        map = "<Tab>",
--        cmap = "<Tab>",
--        hopout = true,
--        do_nothing_if_fail = false,
--      },
--    },
--  },
--  { "windwp/nvim-spectre", event = "VeryLazy", config = "plugins.spectre" },
--  { "tpope/vim-repeat", event = "VeryLazy", lazy = true },
--  { "folke/which-key.nvim", event = "VeryLazy", config = "plugins.which-key" },
--  { "dracula/vim", as = "dracula" },
--  { "catppuccin/nvim", name = "catppuccin", lazy = true, config = "plugins.catppuccin" },
--  { "projekt0n/github-nvim-theme", lazy = true, config = "plugins.github" },
--  { "ellisonleao/gruvbox.nvim", lazy = true, config = "plugins.gruvbox" },
--  { "akinsho/horizon.nvim", lazy = true, config = "plugins.horizon" },
--  { "EdenEast/nightfox.nvim", lazy = true, config = "plugins.nightfox" },
--  { "rose-pine/neovim", lazy = true, name = "rose-pine", config = "plugins.rose-pine" },
--  { "kevinhwang91/nvim-ibus-sw", event = "InsertLeave", opts = {} },
--  {
--    "danymat/neogen",
--    opts = { snippet_engine = "luasnip" },
--    keys = {
--      {
--        "<Leader>ia",
--        function() require("neogen").generate() end,
--        desc = "Annotations",
--      },
--    },
--  },
--  {
--    "kristijanhusak/vim-carbon-now-sh",
--    keys = {
--      {
--        "<F2>",
--        ":CarbonNowSh<CR>",
--        mode = { "v", "n" },
--        desc = "Take code snapshot",
--      },
--    },
--  },
--  {
--    "cseickel/diagnostic-window.nvim",
--    dependencies = { "MunifTanjim/nui.nvim" },
--    event = "LspAttach",
--    init = function() vim.keymap.set("n", ";d", ":DiagWindowShow<CR>", { desc = "Show diagnostic window" }) end,
--  },
--  {
--    "stevearc/conform.nvim",
--    event = "LspAttach",
--    config = "plugins.conform",
--  },
--  {
--    "mfussenegger/nvim-lint",
--    ft = {
--      "javascript",
--      "javascriptreact",
--      "lua",
--      "python",
--      "rst",
--      "ruby",
--      "sh",
--      "typescript",
--      "typescriptreact",
--      "vim",
--      "yaml",
--    },
--    opts = {
--      linters_by_ft = {
--        javascript = { "eslint_d" },
--        javascriptreact = { "eslint_d" },
--        lua = { "luacheck" },
--        python = { "mypy", "pylint" },
--        rst = { "rstlint" },
--        sh = { "shellcheck" },
--        ruby = { "standardrb" },
--        typescript = { "eslint_d" },
--        typescriptreact = { "eslint_d" },
--        vim = { "vint" },
--        yaml = { "yamllint" },
--      },
--      linters = {},
--    },
--    config = function(_, opts)
--      local uv = vim.uv or vim.loop
--      local lint = require("lint")
--      lint.linters_by_ft = opts.linters_by_ft
--      for k, v in pairs(opts.linters) do
--        lint.linters[k] = v
--      end
--      local timer = assert(uv.new_timer())
--      local DEBOUNCE_MS = 500
--      local aug = vim.api.nvim_create_augroup("Lint", { clear = true })
--      vim.api.nvim_create_autocmd({ "BufEnter", "BufWritePost", "TextChanged", "InsertLeave" }, {
--        group = aug,
--        callback = function()
--          local bufnr = vim.api.nvim_get_current_buf()
--          timer:stop()
--          timer:start(
--            DEBOUNCE_MS,
--            0,
--            vim.schedule_wrap(function()
--              if vim.api.nvim_buf_is_valid(bufnr) then
--                vim.api.nvim_buf_call(bufnr, function() lint.try_lint(nil, { ignore_errors = true }) end)
--              end
--            end)
--          )
--        end,
--      })
--      lint.try_lint(nil, { ignore_errors = true })
--    end,
--  },
--}
--
---- { == Transform to LazySpec Table ==> =======================================
--
-----Config load helper
-----@param plugin_config string
-----@param eager? "eager"
--local function get(plugin_config, eager)
--  if (plugin_config:match("plugins") or plugin_config:match("colorschemes")) and not plugin_config:match("meg") then
--    plugin_config = "meg." .. plugin_config
--  end
--
--  if eager == "eager" then return function() require(plugin_config) end end
--
--  return function()
--    -- scheduled loading the majority of config files - results in 30-35% faster startup
--    vim.schedule(function() require(plugin_config) end)
--  end
--end
--
--for i, module in ipairs(modules) do
--  if type(module) == "string" then goto continue end
--
--  -- handle config string values (paths) else keep the module.config value
--  if type(module.config) == "string" then
--    if module.dir and module.dir:match("meg") and not module.config:match("meg") then
--      module.config = "meg." .. module.config
--    end
--    if module.eager then
--      ---@diagnostic disable-next-line: param-type-mismatch
--      module.config = get(module.config, "eager")
--    else
--      ---@diagnostic disable-next-line: param-type-mismatch
--      module.config = get(module.config)
--    end
--  end
--
--  -- remove custom fields
--  if module.eager then module.eager = nil end
--
--  ::continue::
--  modules[i] = module
--end
---- <== }
--
---- { == Load Setup ==> ========================================================
--
--lazy.setup(modules, {
--  change_detection = { enabled = false },
--  ui = { border = "rounded" },
--  dev = { path = "~/code/neovim-plugins" },
--  install = { missing = true },
--  performance = {
--    cache = { enabled = true },
--    rtp = {
--      disabled_plugins = {
--        "gzip",
--        "matchit",
--        "matchparen",
--        "netrwPlugin",
--        "tarPlugin",
--        "tohtml",
--        "tutor",
--        "zipPlugin",
--        "spellfile",
--      },
--    },
--  },
--})
----- <== }
--
---- { == Events ==> ============================================================
--
---- Add path for easy `gf` to the config file of a plugin in `get "<plugins.pluginname">` functions above
--nx.au({
--  "BufEnter",
--  pattern = { vim.fn.stdpath("config") .. "*/init.lua" },
--  callback = function()
--    vim.opt_local.path = { ",,", vim.fn.stdpath("config") .. "/lua/meg/" }
--    vim.cmd("setlocal inex=tr(v:fname,'.','/')")
--  end,
--})
---- <== }
--
----- { == Keymaps ==> ===========================================================
--
--nx.map({ "<leader>P", "<Cmd>Lazy<CR>", desc = "Plugin Manager" })
----- <== }
