#!/usr/bin/env bash

# yabai - is a tiling manager for macos based on binary space partitioning.

# Load the scripting-addition into Docker.app. Installs and updates the scripting-addition when necessary.
# Path is /Library/ScriptingAdditions/yabai.osax.
# System Integrity Protection must be partially disabled.
# yabai --message signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

defaults write .GlobalPreferences com.apple.mouse.scaling -1

BAR_HEIGHT=$(sketchybar --query bar | jq -r '.height')

GENERAL=(
    external_bar all:"${BAR_HEIGHT}":0
    split_type auto
    split_ratio 0.5
    auto_balance off
    auto_padding on
)

WINDOWS=(
    window_placement second_child
    window_shadow float
    window_opacity on
    window_zoom_persist on
    active_window_opacity 0.97
    normal_window_opacity 0.92
    window_animation_easing ease_out_quint
    insert_feedback_color 0xff9dd274
    window_animation_duration 0.25
    window_origin_display default
    window_opacity_duration 0.2
)

LAYOUT=(
    layout bsp
    top_padding 8
    bottom_padding 8
    left_padding 8
    right_padding 8
    window_gap 10
)

MOUSE=(
    mouse_modifier fn
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap
    mouse_follows_focus off
    focus_follows_mouse off
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Raycast|Activity Monitor)$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

echo "yabai configuration loaded.."
