modify_font cell_width 100%
modify_font cell_height 100%
modify_font underline_position 0
modify_font baseline 0
modify_font underline_position 0

font_family FiraCode Nerd Font Mono Light
bold_font   FiraCode Nerd Font Mono SemiBold
italic_font BlexMono Nerd Font Mono Thin Italic
bold_italic_font BlexMono Nerd Font Mono Medium Italic

font_size 20.0
adjust_line_height 5
