# starship.toml

add_newline = false
palette = "default"

format = """
[╭](fg:separator)\
$status\
$directory\
$git_branch\
$cmd_duration\
$line_break\
[╰](fg:separator)\
$character\
"""

###########################################

[palettes.default]
prompt_ok  = "#8047c1"
prompt_err = "#e23140"
icon       = "#161514"
separator  = "#35312c"
background = "#7c7f93"
directory  = "#9f31e2"
duration   = "#E4FF30"
status     = "#e23140"
branch     = "#FF3EA5"

[palettes.catppuccin-latte]
prompt_ok  = "#40a02b"
prompt_err = "#d20f39"
icon       = "#bcc0cc"
separator  = "#5c5f77"
background = "#eff1f5"
directory  = "#8839ef"
duration   = "#df8e1d"
status     = "#dd7878"
branch     = "#ea76cb"

[palettes.catppuccin-mocha]
prompt_ok  = "#a6e3a1"
prompt_err = "#f38ba8"
icon       = "#f5e0dc"
separator  = "#74c7ec"
background = "#313244"
directory  = "#cba6f7"
duration   = "#fab387"
status     = "#f5c2e7"
branch     = "#89b4fa"

###########################################

[character]
success_symbol = "[❯](fg:prompt_ok)"
error_symbol = "[❯](fg:prompt_err)"

[directory]
format = "[─](fg:separator)[](fg:directory)[](fg:icon bg:directory)[](fg:directory bg:background)[ $path](bg:background)[](fg:background)"
truncate_to_repo = false
truncation_length = 0

[status]
format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $pipestatus](bg:background)[](fg:background)"
disabled = false

[git_branch]
format = "[─](fg:separator)[](fg:branch)[](fg:icon bg:branch)[](fg:branch bg:background)[ $branch](bg:background)[](fg:background)"
disabled = false

[cmd_duration]
format = "[─](fg:separator)[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
min_time = 1000

[time]
format = "[](fg:duration)[󰥔](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background)"
disabled = false
