# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭╴](bold green_dark)$all
$battery
[╰╴](bold green_dark)$character
"""
right_format = """$time $cmd_duration"""
add_newline = true
command_timeout = 10_000
palette = 'lover_light'

aws.disabled = true
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = false
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = false
nodejs.disabled = false
java.disabled = true
golang.disabled = true
conda.disabled = true
container.disabled = true
gcloud.disabled = true
localip.disabled = true
php.disabled = true
vagrant.disabled = true
git_metrics.disabled = true

[palettes.lover_light]
background = "#faf4ed"  # Lover's light background color
foreground = "#575279"
selection = "#dfdad9"
comment = "#907aa9"
red = "#D4618F"   # Lover's light 'Charm' color
green = "#286983"
yellow = "#F5E2B1"  # Lover's light 'Wheat' color
blue = "#56949f"
purple = "#CDAAD4"  # Lover's light 'Light Wisteria' color
cyan = "#6EB0E5"    # Lover's light 'Seagull' color
background_dark = "#1e1a27"
foreground_dark = "#dcd6f4"
selection_dark = "#2d283d"
comment_dark = "#7c7895"
red_dark = "#d75098"
green_dark = "#90cf8b"
yellow_dark = "#d1c467"
blue_dark = "#8a92c2"
purple_dark = "#d48fdc"
cyan_dark = "#8fcac9"
background_light = "#33303f"
foreground_light = "#f3f0ff"
selection_light = "#4a445b"
comment_light = "#a9a4c3"
red_light = "#ff7ebd"
green_light = "#ccf7bf"
yellow_light = "#f3ec9a"
blue_light = "#c9cde6"
purple_light = "#f1d9f6"
cyan_light = "#c9f1f0"
darkest_pink = "#B00544"

[line_break]
disabled = true

[character]
format = "$symbol "
success_symbol = "[󰔰](green_dark bold)"
error_symbol = "[](red)"
vimcmd_symbol = "[  ](yellow)"

[username]
format = "[ $user]($style) "
style_root = "bold blue"
style_user = "bold cyan"
disabled = true

[hostname]
ssh_only = true
format = "[](fg:blue bg:none)[$ssh_symbol](fg:blue_dark bg:blue)[](fg:blue bg:blue)[ $hostname]($style)[](fg:blue bg:none) "
style = "fg:bold blue_dark bg:blue"
ssh_symbol = ""
trim_at = "-"
disabled = false

[ruby]
symbol = " "
format = "[](fg:purple bg:none)[$symbol](fg:foreground bg:purple)[](bg:purple_light fg:purple)[ $version]($style)[](fg:purple_light bg:none) "
style = "fg:foreground bg:purple_light"

[git_branch]
symbol = ""
# symbol = "🌱 "
truncation_length = 7
truncation_symbol = ""
format = "[](fg:yellow bg:none)[$symbol](fg:yellow_dark bg:yellow)[](fg:yellow bg:yellow)[$branch]($style)[](fg:yellow bg:none) "
style = "bold fg:yellow_dark bg:yellow"

[git_commit]
commit_hash_length = 7
disabled = false
tag_symbol = " "
tag_disabled = false
format = "[ $hash$tag]($style) "

[git_status]
ignore_submodules = true
format="[](fg:cyan_light bg:none)[$all_status$ahead_behind](fg:cyan bg:cyan_light)[](fg:cyan_light bg:none)"
conflicted = "⚔️"
ahead = "🏎️💨×${count}"
behind = "🐢×${count}"
diverged = "🔱🏎️💨×${ahead_count}🐢×${behind_count}"
untracked = "🛤️ ×${count}"
stashed = "📦"
modified = "📝×${count}"
staged = "🗃️ ×${count}"
renamed = "📛×${count}"
deleted = "🗑️ ×${count}"

[git_state]
merge = " MERGING"
rebase = " REBASING"
cherry_pick =  " PICKING"
style = "bold red"
revert = " REVERTING"
bisect = " BISECTING"

[directory]
read_only = " "
format = "[](fg:purple_light bg:none)[](fg:purple_dark bg:purple_light)[](fg:purple_light bg:purple_light)[$path]($style)[](fg:purple_light bg:none) "
style = "bold italic fg:purple_dark bg:purple_light"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"~" = " ~"
" ~/Documents" = "~/Documents"
" ~/Downloads" = " ~/Downloads"
" ~/Desktop"   = "󰇅~/Desktop"
" ~/Music"     = " ~/Music"
" ~/Pictures"  = " ~/Pictures"
" ~/Library"   = " ~/Library"
" ~/Dropbox"   = " ~/Dropbox"
" ~/code"      = "👩‍💻~/code"
" ~/dev"       = "👩‍💻~/dev"
" ~/workspace" = "💻 ~/workspace"
" ~/.dotfiles" = " dots"

[docker_context]
symbol = " "

[time]
disabled = false
format="[](fg:red_light bg:none)[💖](fg:red_light bg:red_light)[](fg:red_light bg:red_light)[ $time]($style)[](fg:red_light bg:none)"
time_format = "%l:%m%p" #change to %R to only have HH:MM
style="fg:darkest_pink bg:red_light"

[cmd_duration]
min_time = 1
format = "[]($style)[[󰔟 ](bg:green_light fg:green_dark)$duration](bg:green_light fg:green_dark)[ ]($style)"
disabled = false
style = "bg:none fg:green_light"

[battery]
full_symbol = "󰂄 "
charging_symbol = " "
discharging_symbol = "󰂅 "

[[battery.display]]
threshold = 25
style = "red"

[[battery.display]]
threshold = 50
style = "yellow"

[[battery.display]]
threshold = 101
style = "cyan_dark"

[os.symbols]
Alpine = ""
Arch = ""
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Linux = ""
Macos = ""
Mint = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Ubuntu = ""
Unknown = ""
Windows = ""
