# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """╭╴$all """
right_format = """$time $cmd_duration"""
add_newline = true
command_timeout = 10_000
palette = 'hardhacker'

aws.disabled = false
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = false
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = false
nodejs.disabled = false
java.disabled = true
golang.disabled = true
conda.disabled = true
container.disabled = true
gcloud.disabled = true
localip.disabled = true
php.disabled = true
vagrant.disabled = true
git_metrics.disabled = false

[palettes.hardhacker]
background = "#282433"
foreground = "#eee9fc"
selection = "#3f3951"
comment = "#938aad"
red = "#e965a5"
green = "#b1f2a7"
yellow = "#ebde76"
blue = "#b1baf4"
purple = "#e192ef"
cyan = "#b3f4f3"
background_dark = "#1e1a27"
foreground_dark = "#dcd6f4"
selection_dark = "#2d283d"
comment_dark = "#7c7895"
red_dark = "#d75098"
green_dark = "#90cf8b"
yellow_dark = "#d1c467"
blue_dark = "#8a92c2"
purple_dark = "#d48fdc"
cyan_dark = "#8fcac9"
background_light = "#33303f"
foreground_light = "#f3f0ff"
selection_light = "#4a445b"
comment_light = "#a9a4c3"
red_light = "#ff7ebd"
green_light = "#ccf7bf"
yellow_light = "#f3ec9a"
blue_light = "#c9cde6"
purple_light = "#f1d9f6"
cyan_light = "#c9f1f0"
darkest_pink = "#B00544"

[palettes.rainbow]
red = "#F77976"
orange = "#FFAB00"
yellow = "#FDF148"
green  = "#A0E426"
blue = "#52E3E1"
indigo = "#AEA9FE"
violet = "#D6B1FC"
dark_red = "#FF5C90"
dark_orange = "#FF964B"
dark_yellow = "#FFEC5C"
dark_green = "#4F871A"
dark_blue = "#318AD8"
dark_indigo = "#645AFD"
dark_violet = "#AE62F9"
lavendar = "#D883FF"
dark_lavendar = "#9336FD"
pink = "#FFC8DD"
dark_pink = "#F050AE"
baby_blue = "#BDE0FE"

[ruby]
symbol = " "
format = "[](fg:purple bg:none)[$symbol](fg:foreground bg:purple)[](bg:purple_light fg:purple)[ $version]($style)[](fg:purple_light bg:none) "
style = "fg:foreground bg:purple_light"

[character]
format = "\n╰╴$symbol "
success_symbol = "[⟶](green bold)"
error_symbol = "[](red)"
vicmd_symbol = "[](yellow)"

[username]
format = "[ $user]($style) "
style_root = "bold blue"
style_user = "bold cyan"
disabled = true

[hostname]
ssh_only = true
format = "[](fg:blue bg:none)[$ssh_symbol](fg:blue_dark bg:blue)[](fg:blue bg:blue)[ $hostname]($style)[](fg:blue bg:none) "
style = "fg:bold blue_dark bg:blue"
ssh_symbol = ""
trim_at = "-"
disabled = false

[git_branch]
symbol = ""
# symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""
format = "[](fg:cyan bg:none)[$symbol](fg:blue_dark bg:cyan)[](fg:cyan bg:cyan)[$branch]($style)[](fg:cyan bg:none) "
style = "fg:blue_dark bg:cyan"

[git_commit]
tag_symbol = " "
tag_disabled = false
format = "[ $hash$tag]($style) "

[git_status]
# format = "([ $all_status$ahead_behind]($style) )"
format = "[](fg:purple bg:none)[$all_status$ahead_behind]($style)[](fg:purple bg:none)"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "✓"
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"
style = "bg:purple fg:foreground"
# style = "bold yellow"
ignore_submodules = true
# format="[](fg:#4da0ff bg:none)[$all_status$ahead_behind](fg:#282c34 bg:#4da0ff)[](fg:#4da0ff bg:none)"
# conflicted = " 🐗 "
# ahead = " 🐇${count} "
# behind = " 🐢${count} "
# diverged = " 🔱 🐇${ahead_count} 🐢${behind_count} "
# untracked = " 🦅${count} "
# stashed = " 🐫 "
# modified = " 🐾${count} "
# staged = " 🐴${count} "
# renamed = " 🦋${count} "
# deleted = " 🐚${count} "

[git_state]
merge = " MERGING"
rebase = " REBASING"
cherry_pick =  " PICKING"
style = "bold red"
revert = " REVERTING"
bisect = " BISECTING"

[directory]
read_only = " "
format = "[](fg:foreground bg:none)[](fg:blue_dark bg:foreground)[](fg:foreground bg:foreground)[ $path]($style)[](fg:foreground bg:none) "
style = "fg:blue_dark bg:foreground"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"~" = " ~"
" ~/Documents" = " ~/Documents"
" ~/Downloads" = " ~/Downloads"
" ~/Desktop"   = " ~/Desktop"
" ~/Music"     = " ~/Music"
" ~/Pictures"  = " ~/Pictures"
" ~/Library"   = " ~/Library"
" ~/Dropbox"   = " ~/Dropbox"
" ~/code"      = " ~/code"
" ~/dev"       = " ~/dev"
" ~/workspace" = " ~/workspace"
" ~/.dotfiles" = " ~/.dotfiles"

[docker_context]
symbol = " "

[time]
disabled = false
format="[](fg:red_light bg:none)[💖](fg:red_light bg:red_light)[](fg:red_light bg:red_light)[ $time]($style)[](fg:red_light bg:none)"
time_format = "%l:%m%p" #change to %R to only have HH:MM
style="fg:darkest_pink bg:red_light"


[battery]
full_symbol = "󰂄 "
charging_symbol = " "
discharging_symbol = "󰂅 "

[[battery.display]]
threshold = 25
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 101
style = "green"


[cmd_duration]
min_time = 1
format = "[]($style)[[󰔟 ](bg:foreground_light fg:background_light bold)$duration](bg:foreground_light fg:background_light)[ ]($style)"
disabled = false
style = "bg:none fg:foreground_light"

[os.symbols]
Alpine = ""
Arch = ""
CentOS = ""
Debian = ""
Fedora = ""
FreeBSD = ""
Gentoo = ""
Linux = ""
Macos = ""
Mint = ""
NixOS = ""
OpenBSD = ""
openSUSE = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Ubuntu = ""
Unknown = ""
Windows = ""
