#!/usr/bin/env bash
#  ┬ ┬┌─┐┌┐ ┌─┐┬
#  └┬┘├─┤├┴┐├─┤│
#   ┴ ┴ ┴└─┘┴ ┴┴
# Author: Meagan Waller
# Github: github.com/meaganwaller
# Dotfiles Repo: github.com/meaganewaller/dots
# Last edited: July 01, 2023

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# shellcheck source=/dev/null
source ~/.config/yabai/scripts/helper

# Signal Hooks
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=display_added action="~/.config/yabai/scripts/initialization"
yabai -m signal --add event=display_removed action="~/.config/yabai/scripts/initialization"

BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

yabai -m rule --add app=".* Preferences" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="1Password .*" manage=off
yabai -m rule --add app="Bartender" manage=off
yabai -m rule --add app="iStat Menu" manage=off
yabai -m rule --add app="Karabiner" manage=off
yabai -m rule --add title="Preferences" manage=off
yabai -m rule --add app="Installer" manage=off
yabai -m rule --add app="Fantastical Helper" manage=off # Fantastical menu bar drop-down menu

yabai -m rule --add app="kitty" border=on
yabai -m rule --add app="iTerm2" title!="Preferences|Profiles|Updating|^$" border=on

# yabai -m config layout bsp
# yabai -m config split_ratio 0.50
# yabai -m config auto_balance off
# yabai -m config insert_feedback_color 0xaaffcade
# yabai -m config window_placement second_child
# yabai -m config window_topmost off
# yabai -m config window_shadow off
# yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.0
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.95
#
# yabai -m config window_border off
# yabai -m config window_border_width 3
# yabai -m config active_window_border_color 0xff7793d1
# yabai -m config normal_window_border_color 0xff5e6798
#
# yabai -m config mouse_follows_focus off
# yabai -m config focus_follows_mouse off
# yabai -m config mouse_modifier fn
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize
#
# yabai -m config top_padding

yabai -m config external_bar all:"${BAR_HEIGHT}":0
yabai -m config split_type auto
yabai -m config split_ratio 0.5
yabai -m config auto_balance off

yabai -m config  window_placement          second_child
yabai -m config  window_zoom_persist       on
yabai -m config  window_topmost            off
yabai -m config  window_shadow             float
yabai -m config  window_opacity            off
yabai -m config  window_opacity_duration   0.25
yabai -m config  active_window_opacity     0.97
yabai -m config  normal_window_opacity     0.75

yabai -m config  window_border        on
yabai -m config  window_border_hidpi  off
yabai -m config  window_border_blur   off
yabai -m config  window_border_width  4
yabai -m config  window_border_radius 12
yabai -m config  active_window_border_color 0xff7793d1
yabai -m config  normal_window_border_color 0xff5e6798
yabai -m config  insert_feedback_color      0xff7793d1
yabai -m config  mouse_modifier      alt
yabai -m config  mouse_action1       move
yabai -m config  mouse_action2       resize
yabai -m config  mouse_drop_action   swap
yabai -m config  focus_follows_mouse autofocus
yabai -m config  mouse_follows_focus off

LABELS=(
  main
  code
  chat
  mail
  gtd
  doc
  media
  tool
  scratch
)

i=1
for label in "${LABELS[@]}"; do
  yabai -m space "$i" --label "$label"
  i=$((i + 1))
done

yabai -m config --space chat    layout stack window_opacity off
yabai -m config --space media   layout stack window_opacity off
yabai -m config --space scratch layout float
yabai -m config --space tool    layout float
yabai -m config --space mail    window_opacity off \
  left_padding 210 \
  right_padding 210


# Exclude problematic apps from being managed:
yabai -m rule --add label="ColorSlurp" app="^ColorSlurp$" sticky=true layer=above manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
