if status is-interactive
    if type -q starship
        # Universal theme switcher → starship config overlay
        # See docs/adrs/0005-universal-theme-switcher.md. starship has no
        # STARSHIP_PALETTE env var; we point STARSHIP_CONFIG at a complete
        # overlay generated by theme.d/starship on every `theme <name>`.
        # Set BEFORE `starship init` reads the env var.
        function _dotfiles_theme_starship --on-event fish_prompt
            set -l overlay (set -q XDG_STATE_HOME; and echo $XDG_STATE_HOME; or echo $HOME/.local/state)/theme/starship.toml
            if test -r "$overlay"
                set -gx STARSHIP_CONFIG "$overlay"
            else
                set -e STARSHIP_CONFIG
            end
        end

        # Seed STARSHIP_CONFIG on shell start so the first prompt is correct.
        set -l overlay (set -q XDG_STATE_HOME; and echo $XDG_STATE_HOME; or echo $HOME/.local/state)/theme/starship.toml
        if test -r "$overlay"
            set -gx STARSHIP_CONFIG "$overlay"
        end

        starship init fish | source
    end
end
