#!/usr/bin/env sh
#  ┌─┐┬┌─┌─┐┌┬┐┌─┐┬ ┬┬ ┬┌┐ ┌─┐┬─┐
#  └─┐├┴┐├┤  │ │  ├─┤└┬┘├┴┐├─┤├┬┘
#  └─┘┴ ┴└─┘ ┴ └─┘┴ ┴ ┴ └─┘┴ ┴┴└─
# Last Updated: 2023-11-04
#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

source $HOME/.config/sketchybar/create_bars.sh

FONT="SF Pro"
PADDINGS="3"

HELPER=git.felix.helper
killall helper
(cd "$HOME/.config/sketchybar/helper" && make)
"$HOME/.config/sketchybar/helper/helper" "$HELPER" >/dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

bar=(
  height=45
  color=$BAR_COLOR
  border_width=2
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=5
  margin=10
)

sketchybar --bar "${bar[@]}"

defaults=(
  updates=when_shown
  icon.font="$ICON_FONT:Bold:14.0"
  icon.color="$ICON_COLOR"
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

# source "$ITEM_DIR/apple.sh"
# source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/terminal.sh"
# source "$ITEM_DIR/front_app.sh"

# source "$ITEM_DIR/music.sh"
# source "$ITEM_DIR/prompt.sh"

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/ticktick.sh"
# source "$ITEM_DIR/focus.sh"
source "$ITEM_DIR/power.sh"
# source "$ITEM_DIR/time.sh"
# source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/mail.sh"
# source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/volume.sh"
# source "$ITEM_DIR/brew.sh"

# ###################### FINALIZE ###################
sketchybar -m --update
sketchybar --hotload on

echo "sketchybar configuration loaded.."
