---
name: Build
on:
  pull_request:
  push:
  schedule:
    # Every day at 3am UTC
    - cron: 0 3 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: gem install rake colorize yaml
      - name: Check install
        run: rake install
        env:
          TEST_ENV: true
